# -*- coding: utf-8 -*-
"""Week 1 exercises: 30 HOTS items in four blocks, plus portfolio tasks.
Each item: block (1-4), topic, tag ('analyze'|'evaluate'), q, opts, a (index of correct), why."""

SCOPE = "scientific inquiry and the characteristics and levels of life; atoms, bonds, and water; macromolecules, energy, and enzymes; homeostasis, ecology, and the astrobiology thread."

BLOCKS = [
 (1, "Inquiry, the characteristics of life, and levels of organisation", "§1.1–§1.3"),
 (2, "Atoms, bonds, and water", "§1.4–§1.5"),
 (3, "Macromolecules, energy, and enzymes", "§1.6–§1.7"),
 (4, "Homeostasis, ecology, and the astrobiology thread", "§1.8–§1.10"),
]

ITEMS = [
# ---------------- Block I ----------------
dict(block=1, topic="Falsifiability", tag="evaluate",
 q="Four students propose explanations for why a hot-spring microbe is found only above 70 °C. Which statement is a scientific hypothesis in the strict sense?",
 opts=["The microbe prefers hot water because heat is good for it.",
       "The microbe's key enzymes denature below 70 °C, so it cannot grow in cooler water.",
       "The microbe is adapted to its environment.",
       "Nature has placed the microbe where it belongs."],
 a=1, why="Only B forbids an observation: if cultures grow well at 50 °C, B is refuted. A and C restate the observation in vague terms and forbid nothing; D is not testable at all."),
dict(block=1, topic="Experimental design", tag="analyze",
 q="A researcher grows seedlings under red, blue, and white light, watering the red-light group more because it looked dry. Blue-light seedlings grow tallest. The most serious flaw is that",
 opts=["three light colours are too many for one experiment",
       "watering was not held constant, so light colour is confounded with water",
       "there was no white-light group",
       "seedling height is not a valid dependent variable"],
 a=1, why="A controlled variable was allowed to vary between groups, so any difference could be due to water rather than light. White light was in fact included (it serves as a reference). Three treatment levels are fine, and height is a standard measure."),
dict(block=1, topic="Control groups", tag="analyze",
 q="In the 90 °C growth test from the lecture, a sterile tube of medium is incubated alongside the inoculated tubes. Its function is to",
 opts=["provide extra medium if the culture runs out",
       "show that any turbidity in inoculated tubes is not from contamination or medium breakdown",
       "test whether the medium can grow at 90 °C",
       "increase the sample size for statistics"],
 a=1, why="The sterile control isolates the effect of the inoculum: if it stays clear while inoculated tubes cloud, the turbidity is attributable to the organism. Medium does not 'grow', and a sterile tube adds no replicate of the treatment."),
dict(block=1, topic="Correlation and causation", tag="evaluate",
 q="Across 40 lakes, phosphorus concentration correlates strongly with algal biomass (r = 0.85). Which additional evidence would most strengthen the claim that phosphorus causes algal growth?",
 opts=["A larger survey of 400 lakes with the same correlation",
       "Experimentally adding phosphorus to half of a lake divided by a curtain and observing algal bloom only on the treated side",
       "Finding that algal biomass also correlates with lake depth",
       "A literature review showing other scientists believe phosphorus is the cause"],
 a=1, why="Only manipulation with a matched control establishes causation. More correlational data (A) cannot exclude confounders; C adds another correlation; D is authority, not evidence. This is the classic Lake 226 experiment."),
dict(block=1, topic="Theory versus hypothesis", tag="evaluate",
 q="A commentator writes that 'evolution is only a theory, so it is no more certain than any guess.' The best scientific response is that",
 opts=["evolution has been upgraded from theory to law",
       "in science a theory is a broad explanatory framework supported by many independent lines of evidence, not a tentative guess",
       "theories cannot be tested, so the comparison is fair",
       "evolution is a hypothesis, not a theory"],
 a=1, why="The commentator uses the everyday meaning of 'theory'. Scientific theories (cell theory, germ theory, evolution) are the most robust category of explanation, not the least. Theories are not promoted to laws; laws describe, theories explain."),
dict(block=1, topic="Applying the characteristics of life", tag="evaluate",
 q="A robotic probe returns images of spherical objects on an icy surface that grow by accretion, split when large, and appear to move toward warmer regions. Which single further observation would most change the assessment from 'physical process' toward 'possibly biological'?",
 opts=["The spheres are made of carbon-containing molecules",
       "Daughter spheres differ from parents in a heritable way that affects their survival",
       "The spheres are between 1 and 10 micrometres in diameter",
       "The spheres are found near liquid water"],
 a=1, why="Growth, division, and movement toward gradients all have physical mimics (crystals, bubbles, thermophoresis). Heritable variation with fitness consequences is the one characteristic with no abiotic mimic. Carbon, size, and water raise plausibility but do not discriminate."),
dict(block=1, topic="Emergent properties", tag="analyze",
 q="Which is the best example of an emergent property?",
 opts=["A water molecule has two hydrogen atoms",
       "A phospholipid bilayer separates two compartments and maintains a concentration gradient, though no single phospholipid can",
       "A large rock is heavier than a small rock",
       "A protein contains carbon"],
 a=1, why="Emergence is a property of arrangement that the parts lack. Composition (A, D) and simple additivity (C) are not emergence."),
dict(block=1, topic="Levels of organisation", tag="analyze",
 q="A biologist studies how nutrient runoff from farms changes the abundance of fish, algae, and bacteria in a bay, and how oxygen in the water responds. The level of organisation studied is the",
 opts=["population", "community", "ecosystem", "organism"],
 a=2, why="The study includes several interacting populations (community) plus abiotic components (nutrients, oxygen), which together define the ecosystem level."),

# ---------------- Block II ----------------
dict(block=2, topic="Why carbon", tag="evaluate",
 q="Silicon is more abundant than carbon in Earth's crust and, like carbon, forms four covalent bonds. The strongest chemical reason terrestrial life is carbon-based rather than silicon-based is that",
 opts=["silicon is too heavy to be transported into cells",
       "Si–Si bonds are weak and Si–O bonds are very strong, so silicon in water forms silicate networks rather than stable, versatile chains",
       "silicon cannot form covalent bonds with hydrogen",
       "silicon is radioactive"],
 a=1, why="Carbon's advantage is bond chemistry: strong, comparable C–C, C–H, and C–O bonds allow chains, rings, and multiple bonds in water. Silicon's chemistry in an aqueous, oxygen-rich setting collapses to silicates; its CO₂ analogue is a solid."),
dict(block=2, topic="Bond types", tag="analyze",
 q="Two DNA strands are held together by A–T and G–C pairing. That the strands can be separated by gentle heating (~90 °C) but the sugar-phosphate backbone survives indicates that base pairing uses",
 opts=["covalent bonds", "hydrogen bonds", "ionic bonds in a crystal lattice", "peptide bonds"],
 a=1, why="Individually weak hydrogen bonds (2–3 per pair) break with modest heat while the covalent backbone (hundreds of kJ/mol per bond) does not. This difference is what makes DNA both stable and readable."),
dict(block=2, topic="Polarity and solubility", tag="analyze",
 q="Molecule X consists almost entirely of C–H bonds; molecule Y has several –OH and –NH₂ groups. Predict their behaviour in water.",
 opts=["Both dissolve readily",
       "X aggregates away from water (hydrophobic); Y dissolves by hydrogen bonding (hydrophilic)",
       "X dissolves; Y aggregates",
       "Neither dissolves"],
 a=1, why="C–H bonds are nonpolar; –OH and –NH₂ are polar and hydrogen-bond with water. This is the same rule that drives phospholipid bilayer formation and protein folding."),
dict(block=2, topic="Ionic bonds in water", tag="analyze",
 q="A salt crystal is hard and requires high temperature to melt, yet dissolves within seconds in water. The best explanation is that",
 opts=["water breaks the covalent bonds in salt",
       "polar water molecules surround each ion in hydration shells, overcoming the ionic attraction",
       "salt is a nonpolar molecule",
       "water reacts chemically with salt to form a new compound"],
 a=1, why="Ionic bonds are strong in the dry lattice but weak in water because hydration shells shield the charges. No covalent bonds are involved and no reaction occurs; the ions are simply separated."),
dict(block=2, topic="Specific heat", tag="evaluate",
 q="Two hypothetical planets receive identical sunlight. One is covered by a global ocean of water, the other by an ocean of a liquid with one-quarter of water's specific heat. Which prediction follows?",
 opts=["Both planets have identical day–night temperature ranges",
       "The low-specific-heat planet shows larger day–night and seasonal temperature swings",
       "The water planet shows larger swings because water absorbs more sunlight",
       "The low-specific-heat planet is always colder"],
 a=1, why="Specific heat governs how much temperature changes per unit of energy absorbed or lost. Lower specific heat means larger swings for the same energy flux. Nothing about mean temperature or absorption follows from specific heat alone."),
dict(block=2, topic="Ice density", tag="evaluate",
 q="If water contracted on freezing like most substances, the most important biological consequence for a temperate lake would be that",
 opts=["ice would form at the surface and melt faster in spring",
       "ice would sink and accumulate, so the lake could freeze from the bottom up, eliminating the liquid refuge for organisms",
       "the lake would never freeze",
       "fish would float"],
 a=1, why="Ice floats because hydrogen bonding forms an open lattice ~9% less dense than liquid. Denser ice would sink, exposing new surface water to freezing and progressively solidifying the lake."),
dict(block=2, topic="pH calculation", tag="analyze",
 q="Gastric fluid is about pH 2; blood is about pH 7.4. The hydrogen ion concentration in gastric fluid exceeds that in blood by a factor of roughly",
 opts=["5.4", "54", "250,000", "10⁵·⁴ ≈ 250,000 — but only if the temperature is 25 °C"],
 a=2, why="pH is –log₁₀[H⁺], so the difference of 5.4 units is 10⁵·⁴ ≈ 250,000-fold. The temperature caveat (D) affects the neutral point of water slightly, not the definition of pH or this ratio."),
dict(block=2, topic="Buffers and CO₂", tag="evaluate",
 q="A patient hyperventilates, rapidly blowing off CO₂. Using the carbonic acid–bicarbonate equilibrium, predict the immediate change in blood pH and its direction.",
 opts=["pH falls, because less CO₂ means more acid",
       "pH rises, because removing CO₂ pulls the equilibrium leftward and consumes H⁺",
       "pH is unchanged, because bicarbonate is a perfect buffer",
       "pH falls, because oxygen replaces CO₂"],
 a=1, why="CO₂ + H₂O ⇌ H₂CO₃ ⇌ H⁺ + HCO₃⁻. Removing CO₂ shifts the reaction leftward, combining H⁺ with bicarbonate and raising pH (respiratory alkalosis). Buffers resist but do not eliminate the change."),

# ---------------- Block III ----------------
dict(block=3, topic="Origin-of-life chemistry", tag="evaluate",
 q="Origin-of-life researchers regard the formation of the first polymers as harder to explain than the formation of monomers principally because",
 opts=["monomers are rare in the universe",
       "condensation releases water, so polymer formation is thermodynamically unfavourable in bulk water without enzymes or a driving mechanism",
       "polymers are unstable at all temperatures",
       "monomers cannot bond to each other under any conditions"],
 a=1, why="Le Chatelier's principle: in water, a reaction that produces water is pushed toward reactants. Cells solve this with enzymes and ATP; prebiotic scenarios invoke wet–dry cycling, mineral surfaces, or vents. Monomers, by contrast, form readily (Miller–Urey, meteorites)."),
dict(block=3, topic="Membrane self-assembly", tag="evaluate",
 q="Phospholipids placed in water spontaneously form bilayers and vesicles. Why is this observation important for hypotheses about the origin of life?",
 opts=["It proves that the first cells were phospholipid vesicles",
       "It shows that a bounded compartment can arise from physical self-assembly alone, without enzymes or genetic instructions",
       "It shows that membranes require ATP to form",
       "It shows that lipids were the first genetic material"],
 a=1, why="Compartmentalisation is one of the three hard problems (with polymerisation and heredity). Self-assembly demonstrates a route that needs no prior biology. It does not prove what the first cells were (A), and lipids carry no sequence information (D)."),
dict(block=3, topic="Protein structure", tag="analyze",
 q="An enzyme from a hot-spring archaeon works at 95 °C, while the human version of the same enzyme denatures at 55 °C. Both have similar primary sequences. The most likely basis of the difference is",
 opts=["the archaeal enzyme has no tertiary structure",
       "additional stabilising interactions (ionic bonds, disulfide bridges, hydrophobic packing) hold the archaeal enzyme's fold together at high temperature",
       "the archaeal enzyme is made of D-amino acids",
       "the human enzyme has more peptide bonds"],
 a=1, why="Thermostability comes from the number and arrangement of weak interactions that maintain tertiary structure, not from the covalent backbone. Sequence can be similar while a few substitutions add salt bridges or tighten the hydrophobic core."),
dict(block=3, topic="Chirality as a biosignature", tag="evaluate",
 q="A returned sample contains amino acids with an 80:20 excess of the L form over the D form. Compared with a sample containing only abiotic-looking organics, this finding is",
 opts=["irrelevant, because chirality is not related to life",
       "suggestive of biological origin, because abiotic synthesis yields near-racemic mixtures while terrestrial life uses almost exclusively L forms",
       "proof of Earth-like life",
       "evidence that the sample was heated"],
 a=1, why="Enantiomeric excess is a recognised biosignature class, but 80:20 is suggestive rather than conclusive: some abiotic processes produce modest excesses, contamination must be excluded, and an independent origin might have chosen D. 'Suggestive' is the calibrated word."),
dict(block=3, topic="Second law and life", tag="evaluate",
 q="A student claims that because cells become more ordered as they grow, life violates the second law of thermodynamics. The correct rebuttal is that",
 opts=["living things are exempt from thermodynamic laws",
       "cells increase their internal order only by consuming energy and releasing heat and waste, so total entropy of cell plus surroundings still increases",
       "cells do not actually become more ordered",
       "the second law applies only to gases"],
 a=1, why="The second law applies to the total system. Local order is bought with a larger disorder exported to the surroundings. This is why life needs a continuous energy flux and why it is a disequilibrium state."),
dict(block=3, topic="Enzymes and equilibrium", tag="analyze",
 q="Adding an enzyme to a reaction mixture at equilibrium would be expected to",
 opts=["shift the equilibrium toward products",
       "have no effect on the equilibrium position, though it would speed the approach to equilibrium if the mixture were disturbed",
       "make the reaction exergonic",
       "increase ΔG"],
 a=1, why="Enzymes lower activation energy in both directions equally; they do not change ΔG or the equilibrium constant. At equilibrium there is no net reaction to accelerate."),
dict(block=3, topic="Energy gradients and habitability", tag="evaluate",
 q="Cassini detected molecular hydrogen in the Enceladus plume, and the ocean is thought to contain oxidants such as sulfate and carbon dioxide. In habitability terms, this matters because",
 opts=["hydrogen is a nutrient that all life must eat",
       "a reductant and an oxidant together constitute a redox gradient that a chemolithotrophic metabolism could exploit, satisfying the energy criterion without sunlight",
       "hydrogen proves the ocean is warm",
       "hydrogen is a direct biosignature"],
 a=1, why="Life needs an exploitable free-energy gradient, not sunlight specifically. Terrestrial methanogens live on exactly this H₂ + CO₂ couple. Hydrogen alone is not a biosignature; in fact its abundance suggests it is not being consumed rapidly."),

# ---------------- Block IV ----------------
dict(block=4, topic="Classifying feedback", tag="analyze",
 q="During a fever, a rising body temperature does not trigger sweating until the temperature exceeds about 39 °C, after which sweating brings it back to 39 °C. The best description is",
 opts=["negative feedback has failed",
       "negative feedback is intact, but the set point has been raised",
       "positive feedback is driving the temperature up",
       "the receptors have been destroyed"],
 a=1, why="The loop still opposes deviation, but around a new, higher set point established by pyrogens acting on the hypothalamus. A failed loop would allow unlimited drift; positive feedback would not stabilise at any value."),
dict(block=4, topic="Diagnosing control failure", tag="evaluate",
 q="Three habitats each show a CO₂ control problem. Habitat A: CO₂ drifts steadily upward with no correction. Habitat B: CO₂ swings between 0.2% and 1.2% every two hours. Habitat C: CO₂ is stable but at 1.5%. Match each to the most likely fault.",
 opts=["A: sensor or effector failed; B: excessive gain or delay in the loop; C: set point wrongly configured",
       "A: set point wrong; B: sensor failed; C: excessive gain",
       "A: excessive gain; B: set point wrong; C: sensor failed",
       "All three: sensor failure"],
 a=0, why="Drift indicates no correction (detection or actuation lost). Oscillation indicates over-correction or lag. Stable-but-wrong indicates the loop works but defends the wrong value. This is the same diagnostic logic as in physiology."),
dict(block=4, topic="Positive feedback", tag="analyze",
 q="Which is an example of positive feedback, and why is it not destabilising for the organism?",
 opts=["Insulin lowering glucose; because it is fast",
       "Platelets recruiting more platelets to seal a wound; because an endpoint (the clot) terminates the loop",
       "Sweating lowering temperature; because it is slow",
       "ADH increasing water reabsorption; because it is hormonal"],
 a=1, why="Positive feedback amplifies until a terminating event. Clotting, labour, and the action potential are self-limiting by design. The other three are negative feedback loops."),
dict(block=4, topic="Trophic efficiency", tag="analyze",
 q="A sealed habitat's crop chamber fixes 5,000 kJ of energy per day. If the crew ate only fish raised on those crops, the energy available to the crew would be about",
 opts=["5,000 kJ/day", "500 kJ/day", "50 kJ/day", "4,500 kJ/day"],
 a=2, why="Two transfers at ~10%: crops → fish (500 kJ) → crew (50 kJ). Eating the crops directly makes ~500 kJ available. This is why bioregenerative designs minimise trophic levels."),
dict(block=4, topic="Nitrogen cycle", tag="evaluate",
 q="A habitat design supplies crops with fixed nitrogen only from stored fertiliser, with no recycling of crew waste and no nitrogen-fixing organisms. The critical long-term flaw is that",
 opts=["crops will get too much nitrogen",
       "the habitat's nitrogen is materially closed, so fixed nitrogen lost to waste is not returned and the store will eventually be exhausted",
       "nitrogen gas in the air will poison the crops",
       "denitrifying bacteria will multiply uncontrollably"],
 a=1, why="Matter cycles; it is not created. Without a closed nitrogen loop (waste processing returning ammonium/nitrate, or fixation from the N₂ reservoir), the system runs down. This is an ecological constraint, not an engineering preference."),
dict(block=4, topic="Habitable versus inhabited", tag="evaluate",
 q="A planetary scientist describes a subsurface Martian aquifer as 'habitable'. Which claim is the scientist entitled to make on that basis?",
 opts=["Life exists in the aquifer",
       "The aquifer's solvent, energy, elemental, and stability conditions fall within ranges that known life could tolerate; whether anything lives there is a separate question",
       "Life once existed there",
       "The aquifer contains organic molecules"],
 a=1, why="Habitability is an environmental assessment against stated criteria. Inhabitation requires detection. Conflating the two is the most common error in public discussion of the field."),
dict(block=4, topic="Universal requirement versus terrestrial fact", tag="evaluate",
 q="In writing an operational definition of life for a mission, which item should be treated as a requirement any life must meet, rather than a feature of Earth life that may be contingent?",
 opts=["Uses DNA as its genetic material",
       "Maintains a boundary across which it sustains a chemical difference from its surroundings, using an energy gradient",
       "Uses the same 20 amino acids as terrestrial proteins",
       "Uses ATP as its energy currency"],
 a=1, why="Boundary, disequilibrium, and energy flux follow from thermodynamics and apply to any chemistry. DNA, the specific amino acid set, and ATP are implementations that another origin could have solved differently. A definition built on B is more general and more measurable."),
]

PORTFOLIO = [
 ("Life and biological organisation map (Portfolio Entry 1)",
  "Produce a one-page map with three layers: (1) the levels of organisation from atom to biosphere with one emergent property at each level; (2) the characteristics of life with a non-living counterexample for each and a mark on those you would require before reporting a detection; (3) an operational definition of life in under 100 words, followed by one sentence naming the kind of life your definition would fail to detect.",
  "Grade for accuracy of levels and properties (40%), quality of counterexamples (20%), measurability of the definition (30%), and the honesty of the limitation statement (10%). A definition that omits evolution is acceptable if the limitation sentence acknowledges what is lost."),
 ("Biomolecule and homeostasis analysis",
  "Choose one homeostatic variable (temperature, glucose, pH, or osmolarity). Draw the loop with receptor, control centre, set point, and effector labelled. Identify the macromolecules involved at each step (for example, the enzyme or hormone that acts as the effector signal) and state which macromolecule class each belongs to. Then predict the observable consequence of (a) halving the receptor's sensitivity and (b) doubling the loop delay.",
  "The predictions are the graded element: (a) should describe a widened tolerance band or slower correction, (b) overshoot and oscillation. Credit correct macromolecule classes for hormones (protein or steroid) and enzymes (protein)."),
 ("Concept check: solvent alternatives",
  "In 200 words, evaluate whether the argument 'liquid water is required for life' is a physical requirement or an Earth-based assumption. Use at least three properties of water from §1.5 and state, for each, whether an alternative solvent could supply it.",
  "Strong answers separate properties that follow from polarity (solvent action for ions, hydrogen bonding) from those that are quantitative advantages (specific heat) and name a specific alternative (ammonia, methane) with its temperature range."),
]
