# -*- coding: utf-8 -*-
"""Week 2 exercises: 30 HOTS items in four blocks, plus portfolio tasks."""

SCOPE = "cell theory, size limits, and cell architectures; the membrane and every transport route across it; respiration and photosynthesis as proton-gradient machines; the cell cycle, meiosis, and what a cell leaves behind."

BLOCKS = [
 (1, "Cell theory, size, and cell architectures", "§2.1–§2.3"),
 (2, "Membranes and transport", "§2.4–§2.6"),
 (3, "Respiration and photosynthesis", "§2.7–§2.8"),
 (4, "Division, variation, and the astrobiology thread", "§2.9–§2.10"),
]

ITEMS = [
# ---------------- Block I ----------------
dict(block=1, topic="Resolution versus magnification", tag="analyze",
 q="A student photographs a bacterium at 1,000× with a light microscope, then enlarges the image 10× on screen. The internal ribosomes (about 20 nm) are still invisible. The reason is that",
 opts=["the total magnification of 10,000× is insufficient",
       "the microscope's resolution (~200 nm) cannot separate objects smaller than the wavelength of light, and enlarging the image does not add detail",
       "ribosomes are transparent to all radiation",
       "bacteria have no ribosomes"],
 a=1, why="Resolution is limited by wavelength; digital enlargement magnifies the blur. Electron microscopy is needed for 20 nm objects."),
dict(block=1, topic="Surface-area-to-volume", tag="analyze",
 q="Cell P is a 2 μm cube; cell Q is a 20 μm cube. Compared with Q, P has a surface-area-to-volume ratio that is",
 opts=["10 times larger", "10 times smaller", "100 times larger", "the same, because both are cubes"],
 a=0, why="For a cube, SA/V = 6/s. P: 3 μm⁻¹; Q: 0.3 μm⁻¹. A tenfold size difference gives a tenfold ratio difference in favour of the smaller cell."),
dict(block=1, topic="Size limits and 'nanofossils'", tag="evaluate",
 q="Structures 30–100 nm across in a Martian meteorite were once proposed as fossil bacteria. The strongest cell-biological objection is that",
 opts=["Mars has no water",
       "the smallest known free-living cells are ~200–300 nm because a genome, ribosomes, and a minimal enzyme set cannot fit in a smaller volume",
       "fossils cannot form in rock",
       "bacteria are always larger than 10 μm"],
 a=1, why="A lower size limit follows from the volume needed for the minimal molecular machinery of a self-maintaining cell. Objects well below it are more plausibly mineral artefacts."),
dict(block=1, topic="Classifying a cell", tag="analyze",
 q="A cell has a nucleus, 80S cytoplasmic ribosomes, mitochondria, a cellulose wall, and no centrioles. It is best classified as a",
 opts=["bacterium", "archaeon", "plant cell", "animal cell"],
 a=2, why="Nucleus and 80S ribosomes make it eukaryotic; a cellulose wall and absence of centrioles are plant features. Animal cells lack walls; prokaryotes lack nuclei."),
dict(block=1, topic="Endosymbiosis evidence", tag="evaluate",
 q="Which observation would most weaken the endosymbiotic origin of mitochondria?",
 opts=["Mitochondria have a double membrane",
       "Mitochondrial ribosomes are 70S and inhibited by chloramphenicol",
       "Mitochondrial genes are most similar in sequence to genes in the eukaryotic nucleus rather than to any bacterial group",
       "Mitochondria divide by fission"],
 a=2, why="The theory predicts mitochondrial genes should resemble a specific bacterial lineage (α-proteobacteria), which they do. Closest similarity to the host nucleus instead would remove the strongest line of evidence. The other three are supporting observations."),
dict(block=1, topic="Archaeal membranes", tag="analyze",
 q="Archaea living at 95 °C and pH 2 often have membrane lipids that are ether-linked and span the membrane as a single layer. Compared with a bacterial bilayer, this design",
 opts=["increases fluidity to speed transport",
       "resists heat-driven separation of the leaflets and acid hydrolysis of the head-tail linkage",
       "allows free passage of protons",
       "eliminates the need for membrane proteins"],
 a=1, why="Ether bonds resist hydrolysis at low pH; a covalently linked monolayer cannot come apart when heated. Both stabilise the barrier under extreme conditions."),
dict(block=1, topic="Organelle function from structure", tag="analyze",
 q="A cell type packed with rough ER, prominent Golgi, and many secretory vesicles is most likely specialised for",
 opts=["contraction", "secreting protein such as digestive enzymes or antibodies", "lipid storage", "photosynthesis"],
 a=1, why="Rough ER synthesises secreted proteins, the Golgi packages them, and vesicles export them. This is the profile of pancreatic acinar cells and plasma cells."),
dict(block=1, topic="Endomembrane routing", tag="analyze",
 q="A mutation prevents the addition of the mannose-6-phosphate tag in the Golgi. The most direct consequence is that",
 opts=["proteins cannot enter the nucleus",
       "lysosomal enzymes are secreted from the cell instead of being delivered to lysosomes, so undigested material accumulates",
       "mitochondria stop making ATP",
       "the plasma membrane loses cholesterol"],
 a=1, why="The tag is the sorting address for lysosomal enzymes. Without it they follow the default secretory route. This is the basis of I-cell disease."),

# ---------------- Block II ----------------
dict(block=2, topic="Membrane fluidity", tag="analyze",
 q="Salmon living in near-freezing water are found to have membranes rich in unsaturated fatty acids. The functional reason is that",
 opts=["unsaturated tails pack tightly, strengthening the membrane in cold",
       "the kinks in unsaturated tails prevent tight packing, keeping the membrane fluid at low temperature",
       "unsaturated lipids are cheaper to synthesise",
       "cold water contains more unsaturated fats to absorb"],
 a=1, why="Double bonds create kinks that hold neighbouring lipids apart; without them the bilayer would gel and transport would stop."),
dict(block=2, topic="Selective permeability", tag="analyze",
 q="Which pair correctly matches a substance with how it crosses the plasma membrane?",
 opts=["O₂ — requires an ATP-driven pump", "Na⁺ — simple diffusion through the bilayer", "Glucose — facilitated diffusion via a carrier protein", "Steroid hormone — receptor-mediated endocytosis"],
 a=2, why="Glucose is large and polar and needs a GLUT carrier; O₂ diffuses freely; Na⁺ is charged and needs a channel or pump; steroids are lipid-soluble and diffuse through the bilayer."),
dict(block=2, topic="Tonicity calculation", tag="analyze",
 q="A cell with internal osmolarity 300 mOsm is placed in 150 mM MgCl₂. Predict its behaviour.",
 opts=["No change; the solution is isotonic",
       "It shrinks; MgCl₂ yields three particles, so 150 mM ≈ 450 mOsm, hypertonic",
       "It swells; 150 mM is less than 300",
       "It lyses; divalent ions always cause lysis"],
 a=1, why="Osmolarity counts particles: MgCl₂ → Mg²⁺ + 2 Cl⁻. Water leaves the cell toward the more concentrated exterior."),
dict(block=2, topic="Plant versus animal in hypotonic medium", tag="analyze",
 q="Distilled water is fatal to red blood cells but beneficial to wilted lettuce. The difference arises because",
 opts=["plant cells have no membrane",
       "the cellulose wall resists expansion, so plant cells become turgid rather than bursting",
       "animal cells cannot take up water",
       "plant cells are hypertonic to distilled water and animal cells are not"],
 a=1, why="Both cell types take up water in a hypotonic medium. The wall limits plant cell volume and generates turgor; the wall-less animal cell has no such limit and lyses."),
dict(block=2, topic="Diagnosing transport type", tag="evaluate",
 q="Uptake of solute S by a cell is specific, saturates at high concentration, is unaffected by metabolic poisons, and stops when the external concentration equals the internal. S enters by",
 opts=["simple diffusion", "facilitated diffusion", "primary active transport", "endocytosis"],
 a=1, why="Specificity and saturation indicate a protein; independence from ATP and cessation at equilibrium indicate passive movement. Only facilitated diffusion fits all four."),
dict(block=2, topic="Na⁺/K⁺ pump consequences", tag="evaluate",
 q="Ouabain inhibits Na⁺/K⁺-ATPase. Which set of consequences is correctly predicted for an animal cell?",
 opts=["Membrane potential rises, Na⁺-coupled glucose uptake accelerates, cell shrinks",
       "Membrane potential decays, Na⁺-coupled glucose uptake slows, cell swells",
       "No change; other pumps compensate immediately",
       "Membrane potential decays, glucose uptake accelerates, cell shrinks"],
 a=1, why="Loss of the pump collapses the Na⁺ and K⁺ gradients (potential decays), removes the driving force for secondary active transport (uptake slows), and lets intracellular solute and water rise (swelling)."),
dict(block=2, topic="Secondary active transport", tag="analyze",
 q="Oral rehydration solution contains glucose and sodium together, not sodium alone, because",
 opts=["glucose provides calories",
       "the intestinal sodium–glucose symporter moves both in together, and water follows the absorbed solute",
       "glucose neutralises stomach acid",
       "sodium cannot dissolve without glucose"],
 a=1, why="SGLT1 couples Na⁺ entry (down its gradient) to glucose entry (against its gradient); the solute uptake then draws water osmotically. This is why the therapy works even in cholera, where other mechanisms fail."),
dict(block=2, topic="Gradients as evidence of life", tag="evaluate",
 q="A sample from a subsurface brine contains cell-like particles. Which measurement would most directly distinguish living cells from dead cells or abiotic vesicles?",
 opts=["Presence of lipids in the particles",
       "A maintained membrane potential or ion gradient across the particle boundary that collapses when a metabolic inhibitor is added",
       "Spherical shape",
       "Size between 1 and 5 μm"],
 a=1, why="Lipids, shape, and size are shared by dead cells and abiotic vesicles. A gradient maintained against leakage, and dependent on metabolism, is the signature of ongoing work."),

# ---------------- Block III ----------------
dict(block=3, topic="Role of oxygen", tag="analyze",
 q="Oxygen is described as essential to aerobic respiration, yet it participates directly in none of the reactions of glycolysis or the citric acid cycle. Its actual role is to",
 opts=["oxidise glucose directly in the cytosol",
       "act as the final electron acceptor at the end of the electron transport chain, allowing NADH to be reoxidised",
       "provide the phosphate for ATP",
       "activate the citric acid cycle enzymes"],
 a=1, why="Without an acceptor the chain stalls, NADH accumulates, and the NAD⁺ needed upstream runs out. Oxygen's job is to keep electrons flowing."),
dict(block=3, topic="Pasteur effect", tag="evaluate",
 q="A yeast culture consumes glucose 12 times faster after oxygen is removed, while its growth rate falls. The best explanation is that",
 opts=["oxygen inhibits glucose uptake",
       "fermentation yields only ~2 ATP per glucose versus ~30 aerobically, so far more glucose must be processed to meet energy demand",
       "anaerobic yeast cells are larger",
       "fermentation produces more ATP per glucose"],
 a=1, why="Energy demand is met by consuming more substrate through the low-yield route; growth still falls because total ATP supply is lower."),
dict(block=3, topic="Uncoupling", tag="evaluate",
 q="Dinitrophenol makes the inner mitochondrial membrane leaky to protons. Predicted effects on oxygen consumption and ATP synthesis are",
 opts=["both fall", "oxygen consumption rises while ATP synthesis falls; energy is released as heat", "both rise", "oxygen consumption falls while ATP synthesis rises"],
 a=1, why="Protons bypass ATP synthase, so the gradient never builds; the chain runs faster trying to rebuild it (more O₂ used) but no ATP results. The same mechanism, via uncoupling protein, generates heat in brown fat."),
dict(block=3, topic="Fermentation versus anaerobic respiration", tag="analyze",
 q="A subsurface bacterium oxidises hydrogen and reduces sulfate to sulfide, with no oxygen present, and yields several ATP per hydrogen consumed. This metabolism is",
 opts=["fermentation", "anaerobic respiration using a complete electron transport chain with sulfate as final acceptor", "photosynthesis", "aerobic respiration"],
 a=1, why="Fermentation has no chain and no external acceptor; this organism has both, with sulfate in place of oxygen. Sulfate reducers are major players in sediments and hydrothermal systems."),
dict(block=3, topic="Universality of chemiosmosis", tag="evaluate",
 q="Chemiosmosis is found in mitochondria, chloroplasts, and bacterial membranes. The strongest inference from this distribution is that",
 opts=["it evolved independently three times",
       "it was present in the last common ancestor of all cells, or was inherited by organelles from their bacterial ancestors, making it among the oldest energy-capture mechanisms",
       "it requires oxygen",
       "it is unique to eukaryotes"],
 a=1, why="Near-universal distribution plus the endosymbiotic origin of organelles points to deep ancestry. This is why proton gradients are central to hydrothermal-vent origin-of-life models (Week 11)."),
dict(block=3, topic="Source of photosynthetic oxygen", tag="analyze",
 q="Algae are supplied with water containing ¹⁸O and CO₂ containing ordinary ¹⁶O. The oxygen gas they release is enriched in ¹⁸O. This demonstrates that",
 opts=["CO₂ is split to release O₂",
       "water is the electron donor and the source of released O₂",
       "algae do not perform photosynthesis",
       "isotopes are unstable in cells"],
 a=1, why="The label appears in O₂ only when it starts in water. Photolysis at photosystem II splits water, not carbon dioxide."),
dict(block=3, topic="Photosynthesis without oxygen", tag="evaluate",
 q="An exoplanet shows a strong 'red edge' spectral feature suggestive of pigment-bearing surface life but no detectable atmospheric oxygen. A defensible interpretation is that",
 opts=["the red edge must be a false positive because photosynthesis always makes oxygen",
       "the biosphere could rely on anoxygenic photosynthesis using electron donors such as sulfide or iron, which releases no O₂",
       "oxygen has been consumed entirely by the plants",
       "the planet has no atmosphere"],
 a=1, why="Anoxygenic photosynthesis is older and widespread on Earth; a productive biosphere need not oxygenate its atmosphere. Absence of O₂ is not evidence against photosynthesis."),

# ---------------- Block IV ----------------
dict(block=4, topic="Chromosome counting", tag="analyze",
 q="A cell with 2n = 8 is in anaphase of mitosis. The number of chromosomes moving toward each pole is",
 opts=["4", "8", "16", "2"],
 a=1, why="In anaphase the sister chromatids separate and each becomes a chromosome; 16 chromatids become 16 chromosomes, 8 to each pole. Each daughter cell ends with 2n = 8."),
dict(block=4, topic="Checkpoint logic", tag="evaluate",
 q="A cell line has lost functional p53. Compared with normal cells exposed to the same dose of radiation, these cells are expected to",
 opts=["arrest permanently in G₁",
       "continue through the cycle despite DNA damage, accumulating mutations, and be less likely to undergo apoptosis",
       "repair DNA more efficiently",
       "be unable to enter S phase"],
 a=1, why="p53 halts the cycle and triggers repair or apoptosis in response to damage. Without it, damaged cells proceed and propagate errors, which is why p53 loss is so common in cancer."),
dict(block=4, topic="Spindle inhibitors", tag="analyze",
 q="Colchicine binds tubulin and blocks microtubule assembly. Dividing cells treated with it accumulate in",
 opts=["G₁, because growth stops", "S phase, because replication needs microtubules", "metaphase, because the spindle checkpoint is never satisfied", "cytokinesis, because the cleavage furrow needs microtubules"],
 a=2, why="Without a spindle, kinetochores cannot attach, the spindle checkpoint blocks anaphase, and cells arrest with condensed chromosomes. This is why colchicine is used to prepare karyotypes."),
dict(block=4, topic="Meiosis versus mitosis outcomes", tag="analyze",
 q="Which statement correctly distinguishes the products of the two divisions?",
 opts=["Mitosis produces four haploid cells; meiosis produces two diploid cells",
       "Mitosis produces two diploid cells identical to the parent; meiosis produces four haploid cells that are genetically distinct",
       "Both produce genetically identical cells",
       "Meiosis involves one division; mitosis involves two"],
 a=1, why="Mitosis copies; meiosis halves chromosome number and generates variation through crossing over and independent assortment."),
dict(block=4, topic="Sources of variation", tag="analyze",
 q="Two siblings with the same parents are genetically different mainly because of",
 opts=["mutations acquired during their own lifetimes",
       "crossing over and independent assortment during their parents' meiosis, plus random fertilisation",
       "mitosis in the zygote",
       "different diets"],
 a=1, why="Each parent produces gametes with ~8.4 million chromosome combinations before crossing over is counted; each fertilisation samples one from each. Somatic mutation and diet do not change the inherited genome."),
dict(block=4, topic="Nondisjunction", tag="analyze",
 q="A gamete with two copies of chromosome 21 fertilises a normal gamete. The zygote will have",
 opts=["45 chromosomes", "46 chromosomes", "47 chromosomes, with three copies of chromosome 21", "92 chromosomes"],
 a=2, why="Nondisjunction in one parent produced an n + 1 gamete (24); with a normal gamete (23) the zygote has 47, trisomy 21."),
dict(block=4, topic="Cellular properties and detectability", tag="evaluate",
 q="Of the four cellular properties collected in §2.10 (boundary, maintained gradients, redox metabolism, replication with variation), which can a remote spectroscopic observation of an exoplanet atmosphere address, and which cannot?",
 opts=["It can address all four",
       "It can address redox metabolism through atmospheric disequilibrium, cannot address boundaries or gradients, and cannot address replication with variation",
       "It can address only boundaries, through lipid absorption features",
       "It can address none of them"],
 a=1, why="Atmospheric gas mixtures out of equilibrium are the remote trace of metabolism. Cell boundaries, gradients, and heredity require samples. Knowing which property each method reaches is the core of life-detection design (Week 13)."),
]

PORTFOLIO = [
 ("Annotated cell and transport model (Portfolio Entry 2)",
  "Produce a labelled diagram of one cell type (bacterial, archaeal, plant, or animal) with every structure named and its function stated in one line; five transport events drawn across the membrane, one each of simple diffusion, facilitated diffusion, osmosis, primary active transport, and either secondary active or bulk transport, each annotated with direction relative to gradient and energy source; and a 150-word note on which features would leave a detectable trace after one billion years in sediment.",
  "Rubric: structural accuracy (35%), transport annotations (35%), preservation note (20%), clarity (10%). The preservation note should name lipids and mineralised walls as durable and organelle organisation as not."),
 ("Transport and metabolism simulation",
  "Using any cell-simulation resource or a spreadsheet model, vary external osmolarity from 100 to 900 mOsm for a model cell of 300 mOsm and record predicted volume. Then model ATP yield per glucose under aerobic, fermentative, and sulfate-respiring conditions (use 30, 2, and 4 ATP) and compute the glucose required to supply 10⁹ ATP per second in each case. Present both as graphs with a paragraph of interpretation.",
  "Look for correct recognition that volume responds to total particle concentration, and that substrate demand scales inversely with yield. The graph axes and units are part of the grade."),
 ("Cell comparison brief",
  "Write a 250-word brief comparing a bacterial and an archaeal cell for a habitability assessment of a hot, acidic environment. State which structural features favour each in that setting, which would be preserved as biomarkers, and what an instrument would need to measure to tell the two apart.",
  "Credit ether versus ester lipids, absence of peptidoglycan, monolayer membranes, and the point that both are prokaryotic in organisation so morphology alone cannot distinguish them."),
]
