# -*- coding: utf-8 -*-
"""Teaching and learning plan, transcribed from the syllabus (Weeks 1-15)."""

PLAN = [
 dict(week=1, term=1, slug="ch01", title="Overview of Biological Science and the Chemistry of Life",
   short="Biology and the chemistry of life",
   outcome="Explain the characteristics and levels of life and relate the chemistry of life to energy use and homeostasis.",
   topics="Scientific inquiry; characteristics and levels of life; atoms, water, macromolecules, energy, homeostasis, and introductory ecology.",
   tla="Interactive lecture; life-criteria concept mapping; biomolecule and homeostasis analysis.",
   resources="OpenStax Biology 2e; instructor slides; concept-map template.",
   assessment="Diagnostic task; concept map; short concept check.",
   evaluation="Analytic rubric; answer key; feedback notes.",
   output="Portfolio Entry 1: Life and biological organization map.", cos=["CO1"]),
 dict(week=2, term=1, slug="ch02", title="Cell Structure and Function",
   short="Cells, membranes, and metabolism",
   outcome="Compare prokaryotic and eukaryotic cells and model membrane transport, metabolism, and cell division.",
   topics="Organelles; membranes and transport; enzymes; respiration and photosynthesis; cell cycle, mitosis, and meiosis.",
   tla="Virtual microscopy; cell-model construction; transport and metabolism simulation.",
   resources="OpenStax Biology 2e; virtual-cell or microscopy resources.",
   assessment="Cell comparison; transport model; quiz.",
   evaluation="Scoring guide; item analysis; corrective feedback.",
   output="Portfolio Entry 2: Annotated cell and transport model.", cos=["CO1"]),
 dict(week=3, term=1, slug="ch03", title="Genetics, Evolution, Taxonomy, and Microorganisms",
   short="Genes, selection, and the tree of life",
   outcome="Apply genetic, evolutionary, taxonomic, and phylogenetic reasoning to microorganisms and extremophiles.",
   topics="DNA and gene expression; inheritance; mutation; natural selection; speciation; nomenclature; phylogeny; domains of life; extremophiles.",
   tla="Guided cladogram construction; taxonomic-key exercise; extremophile case analysis.",
   resources="OpenStax Biology 2e; OpenStax Microbiology; taxonomic keys.",
   assessment="Cladogram; classification exercise; case analysis.",
   evaluation="Rubric; accuracy checklist; peer feedback.",
   output="Portfolio Entry 3: Phylogeny and extremophile analysis.", cos=["CO1","CO2"]),
 dict(week=4, term=1, slug="ch04", title="Botany",
   short="Plant structure, transport, and adaptation",
   outcome="Analyze plant structure, transport, reproduction, photosynthesis, tropisms, and ecological adaptations.",
   topics="Plant diversity; tissues and organs; roots, stems, leaves; transport; photosynthesis; reproduction; tropisms; terrestrial adaptations.",
   tla="Specimen classification or virtual herbarium; stomatal or phototropism investigation.",
   resources="OpenStax Biology 2e; plant specimens or virtual herbarium; simulation.",
   assessment="Plant classification; investigation report.",
   evaluation="Investigation rubric; observation checklist.",
   output="Portfolio Entry 4: Plant diversity and physiology brief.", cos=["CO3"]),
 dict(week=5, term=1, slug="ch05", title="Zoology and Comparative Organismal Biology",
   short="Animal body plans and organ systems",
   outcome="Compare major animal groups, body plans, organ systems, reproductive strategies, behaviors, and adaptations.",
   topics="Invertebrates and vertebrates; comparative organ systems; reproduction; behavior; adaptations; ecological relationships.",
   tla="Dichotomous-key activity; comparative animal-system matrix; term synthesis.",
   resources="OpenStax Biology 2e; zoology references; phylogenetic diagrams.",
   assessment="Comparative matrix; Term 1 examination.",
   evaluation="Matrix rubric; examination item analysis.",
   output="Completed Term 1 portfolio and examination.", cos=["CO3"]),
 dict(week=6, term=2, slug="ch06", title="Human Anatomy and Physiology I",
   short="Organisation, tissues, and homeostasis",
   outcome="Use anatomical terminology and explain tissue organization, homeostasis, integumentary functions, and thermoregulation.",
   topics="Anatomical terminology; body cavities; tissue classes; organ systems; feedback control; integumentary system.",
   tla="Virtual anatomy orientation; tissue identification; feedback-loop mapping.",
   resources="OpenStax Anatomy and Physiology 2e; virtual anatomy resources.",
   assessment="Anatomy worksheet; homeostasis map.",
   evaluation="Practical checklist; concept-map rubric.",
   output="A&P Portfolio Entry 1: Organization and homeostasis.", cos=["CO4"]),
 dict(week=7, term=2, slug="ch07", title="Musculoskeletal Systems and Biomechanics",
   short="Levers, force, work, and power",
   outcome="Explain skeletal and muscular organization and apply force, lever, work, and power concepts to human movement.",
   topics="Bone, joints, skeletal muscle, movement, posture, levers, force, work, power, and loading.",
   tla="Joint-lever analysis; movement modeling; quantitative problem solving.",
   resources="OpenStax A&P 2e; OpenStax College Physics 2e; joint models.",
   assessment="Musculoskeletal practical; biomechanics problems.",
   evaluation="Practical rubric; worked-solution key.",
   output="A&P Portfolio Entry 2 and Biophysics Set A.", cos=["CO4","CO5"]),
 dict(week=8, term=2, slug="ch08", title="Nervous, Sensory, and Endocrine Systems",
   short="Signals, senses, and regulation",
   outcome="Analyze nervous, sensory, and endocrine regulation using neural signaling, bioelectricity, optics, and acoustics.",
   topics="CNS/PNS; neural signals; vision; hearing; balance; hormones; stress; membrane potentials; optics; sound.",
   tla="Safe reaction-time or sensory activity; data interpretation; neural-pathway mapping.",
   resources="OpenStax A&P 2e; sensory datasets; simulation tools.",
   assessment="Data interpretation; pathway map; problem set.",
   evaluation="Data-analysis rubric; answer key.",
   output="A&P Portfolio Entry 3 and Biophysics Set B.", cos=["CO4","CO5"]),
 dict(week=9, term=2, slug="ch09", title="Cardiopulmonary and Immune Systems",
   short="Pressure, flow, diffusion, and defence",
   outcome="Trace cardiovascular, lymphatic, immune, and respiratory functions and apply fluid-flow, diffusion, and gas-law principles.",
   topics="Heart; blood; circulation; immunity; ventilation; gas exchange; pressure-flow relations; diffusion; gas laws.",
   tla="Cardiopulmonary data analysis; pressure-flow or gas-exchange case.",
   resources="OpenStax A&P 2e; cardiopulmonary datasets; physics reference.",
   assessment="Case analysis; graph interpretation; concept check.",
   evaluation="Case rubric; graph-analysis checklist.",
   output="A&P Portfolio Entry 4 and biophysics case.", cos=["CO4","CO5"]),
 dict(week=10, term=2, slug="ch10", title="Integrated Homeostasis",
   short="Digestion, metabolism, and fluid balance",
   outcome="Integrate digestive, metabolic, urinary, reproductive, and developmental systems through homeostatic regulation.",
   topics="Digestion; nutrition; metabolism; renal function; osmosis; fluid-electrolyte balance; reproduction; development.",
   tla="Fluid-balance case; integrated organ-system map; term synthesis.",
   resources="OpenStax A&P 2e; metabolism and renal-system diagrams.",
   assessment="Homeostasis map; Term 2 examination.",
   evaluation="Systems-map rubric; examination item analysis.",
   output="Completed Term 2 portfolio and examination.", cos=["CO4","CO5"]),
 dict(week=11, term=3, slug="ch11", title="Foundations of Astrobiology and Origins of Life",
   short="Prebiotic chemistry and early Earth",
   outcome="Explain astrobiology's core questions and evaluate scientific hypotheses concerning the origin and early evolution of life.",
   topics="Cosmic elements; prebiotic chemistry; early Earth; origin-of-life hypotheses; extremophiles; habitability.",
   tla="Evidence-ranking exercise; origin-of-life debate; operational definition of habitability.",
   resources="NASA Astrobiology; instructor-selected peer-reviewed sources.",
   assessment="Evidence brief; concept check.",
   evaluation="Evidence-quality rubric; source checklist.",
   output="Astrobiology Notebook Entry 1: Origins and habitability.", cos=["CO6"]),
 dict(week=12, term=3, slug="ch12", title="Planetary Habitability and Comparative Worlds",
   short="Habitable zones, Mars, icy moons, exoplanets",
   outcome="Evaluate the habitability of planetary environments using solvent, energy, chemistry, stability, and time criteria.",
   topics="Habitable zones; atmospheres and geology; Mars; Venus; icy moons; Titan; exoplanets; Earth analogues.",
   tla="Comparative-world analysis; habitability-matrix workshop.",
   resources="NASA Solar System resources; exoplanet data; planetary datasets.",
   assessment="Habitability matrix; data interpretation.",
   evaluation="Matrix rubric; evidence checklist.",
   output="Astrobiology Notebook Entry 2: Comparative habitability.", cos=["CO6"]),
 dict(week=13, term=3, slug="ch13", title="Biosignatures and Life-Detection Science",
   short="Signals, controls, and false positives",
   outcome="Interpret potential biosignatures and design a life-detection sequence that addresses controls, contamination, and ambiguity.",
   topics="Molecular, chemical, morphological, isotopic, and atmospheric signatures; technosignatures; instruments; false positives and negatives.",
   tla="Spectral or mission-data interpretation; staged life-detection design.",
   resources="NASA Astrobiology resources; sample spectra or mission datasets.",
   assessment="Life-detection case study; method design.",
   evaluation="Case-study rubric; validity checklist.",
   output="Astrobiology Case Study: Biosignature evaluation.", cos=["CO7"]),
 dict(week=14, term=3, slug="ch14", title="Space Life Science: Organisms and Humans Beyond Earth",
   short="Gravity, radiation, and closed ecosystems",
   outcome="Evaluate how altered gravity, radiation, and closed environments affect microbes, plants, animals, and humans.",
   topics="Model organisms; space crops; microbiomes; altered gravity; radiation; closed ecosystems; human hazards and countermeasures.",
   tla="Closed-biosphere model or space-biology experiment design; capstone workshop and peer review.",
   resources="NASA Biological and Physical Sciences; NASA human-spaceflight resources.",
   assessment="Experiment design; capstone draft; peer review.",
   evaluation="Design rubric; peer-review protocol.",
   output="Capstone draft: Investigation and habitability assessment.", cos=["CO7"]),
 dict(week=15, term=3, slug="ch15", title="Planetary Protection, Ethics, and the Future of Life in Space",
   short="Contamination, ethics, and course synthesis",
   outcome="Apply planetary-protection and ethical principles and defend an evidence-based astrobiological investigation.",
   topics="Forward/backward contamination; sample return; research and settlement ethics; uncertainty; course integration.",
   tla="Capstone presentation and defense; course synthesis; reflective discussion.",
   resources="NASA planetary-protection resources; course evidence portfolio.",
   assessment="Capstone; Term 3 examination; final reflection.",
   evaluation="Capstone rubric; oral-defense rubric; item analysis.",
   output="Final capstone, peer review, and integrative assessment.", cos=["CO8"]),
]
