# -*- coding: utf-8 -*-
CONTENT = {}

CONTENT["ch01"] = dict(
 bridge=("Astrobiology cannot search for life without an operational definition of it. Everything in this first week "
         "is a working definition under construction: if a probe returns a chemical pattern from Enceladus, the "
         "criteria you build here are the criteria you will argue from."),
 sections=[
  ("Why a definition of life is hard", [
    "Biology usually describes life by listing properties: organisation, metabolism, growth, response to stimuli, homeostasis, reproduction, heredity, and adaptation through populations. Each property is satisfied by something non-living. Crystals grow and self-organise. Flames metabolise and respond. Viruses carry heredity but borrow the machinery to express it.",
    "The list is therefore a family resemblance rather than a test. NASA's working formulation, that life is a self-sustaining chemical system capable of Darwinian evolution, is deliberately narrow: it prioritises the one property that produces open-ended complexity. Notice what it costs. A sterile, non-reproducing chemical system that used energy and maintained a boundary would fail the test even though it would astonish any laboratory that found it."],
   ["emergent property","Darwinian evolution","operational definition"]),
  ("Levels of organisation", [
    "Life is organised hierarchically, from atoms and molecules up through organelles, cells, tissues, organs, organ systems, organisms, populations, communities, ecosystems, and the biosphere. Each level has properties that the level below does not: a phospholipid does not have a concentration gradient, but a membrane does.",
    "The cell is the pivot of the hierarchy. Below it, chemistry; at and above it, biology. This is why astrobiological life-detection concentrates so heavily on membranes, cell-like morphology, and the chemical asymmetries a bounded compartment can maintain against its surroundings."],
   ["hierarchy","emergence","cell theory"]),
  ("The chemistry that makes it work", [
    "Life on Earth is built from carbon, hydrogen, nitrogen, oxygen, phosphorus, and sulfur (CHNOPS), assembled into four macromolecule classes: carbohydrates, lipids, proteins, and nucleic acids. Carbon dominates because it forms four stable covalent bonds and links to itself in chains and rings, allowing an effectively unlimited molecular vocabulary.",
    "Water is the second structural commitment. Its polarity dissolves ions and polar molecules, its hydrogen bonding gives it high specific heat and a high heat of vaporisation, and its expansion on freezing insulates the liquid below. These properties buffer temperature and permit reaction chemistry in a narrow, stable range, which is why the search for habitable worlds is largely a search for liquid solvents."],
   ["CHNOPS","macromolecule","polarity","specific heat"]),
  ("Energy, entropy, and homeostasis", [
    "Organisms do not violate the second law of thermodynamics; they export entropy. A cell maintains internal order by continuously degrading a high-quality energy source and releasing heat and disordered waste. Cut off the flux and the structure decays. This is why the physical signature of life is a persistent chemical disequilibrium, not a molecule.",
    "Homeostasis is the regulatory expression of that flux: variables such as temperature, pH, and solute concentration are held within tolerable ranges by negative feedback. A receptor detects deviation, a control centre compares it to a set point, and an effector opposes the change. Positive feedback amplifies instead, which is useful for processes that need to finish quickly, such as clotting or childbirth."],
   ["thermodynamic disequilibrium","negative feedback","set point","free energy"]),
 ],
 figure=dict(kind="stack", title="Levels of biological organisation",
   caption="Each level acquires properties absent from the one below. The cell is the transition from chemistry to biology, and the level most life-detection instruments target.",
   items=["Biosphere","Ecosystem","Community","Population","Organism","Organ system","Tissue","Cell","Molecule","Atom"]),
 practice=[
  dict(q="A probe finds vesicle-like structures on a cold moon that grow, split, and use ambient chemical energy, but show no heritable variation between generations. Under NASA's working definition of life, the most defensible conclusion is that the structures are",
    opts=["living, because they metabolise and reproduce","not demonstrably alive, because Darwinian evolution has not been shown","not alive, because vesicles are always abiotic","living, because self-assembly requires biological catalysis"],
    a=1, why="The working definition privileges a self-sustaining chemical system capable of Darwinian evolution. Growth and division alone are reproduced by purely physical vesicle systems; without heritable variation there is no basis for the evolutionary criterion."),
  dict(q="The claim that a property is emergent at a given level of organisation means that the property",
    opts=["cannot be predicted from any lower-level knowledge in principle","arises from interactions among components and is absent in the isolated components","is unique to living systems","is caused by a supernatural organising force"],
    a=1, why="Emergence is about interaction, not mystery. A concentration gradient exists for a membrane-bounded compartment but not for a lone phospholipid."),
  dict(q="Carbon rather than silicon dominates terrestrial biochemistry mainly because carbon",
    opts=["is more abundant than silicon in Earth's crust","forms four stable bonds and long stable chains with itself","has a lower atomic mass and diffuses faster","forms only single bonds, simplifying reactions"],
    a=1, why="Silicon is more abundant in Earth's crust than carbon. Carbon wins on chemistry: catenation and stable multiple bonds give an enormous space of stable molecules; Si-Si and Si=O chemistry is far more limited in aqueous conditions."),
  dict(q="A world with liquid ethane seas instead of water would most directly challenge which assumption embedded in Earth-based habitability criteria?",
    opts=["that life needs carbon","that life needs a polar solvent that dissolves ionic and polar species","that life must be cellular","that life must use nucleic acids"],
    a=1, why="Ethane is nonpolar and would not support the ion chemistry that water enables. Membrane structure and macromolecule folding would need entirely different chemistry, which is precisely the interest of Titan."),
  dict(q="Which observation would count as the strongest physical evidence of biological activity, independent of any assumption about biochemistry?",
    opts=["organic molecules in a sample","a persistent chemical disequilibrium sustained against relaxation to equilibrium","liquid water at the surface","layered mineral structures"],
    a=1, why="Organics, water, and layered minerals all have abiotic routes. A maintained disequilibrium requires a continuous energy-dissipating process, which is the thermodynamic signature that motivates atmospheric biosignature searches."),
  dict(q="In a negative feedback loop, the effector's action",
    opts=["amplifies the original deviation from the set point","opposes the original deviation from the set point","replaces the set point with a new one","measures the controlled variable"],
    a=1, why="Negative feedback opposes deviation, returning the variable toward its set point. Amplification is positive feedback, and detection is the receptor's role."),
  dict(q="Water's high specific heat capacity matters for habitability primarily because it",
    opts=["allows organisms to store more chemical energy","buffers temperature swings, keeping conditions within reaction-compatible ranges","increases the rate of enzyme catalysis directly","prevents dissolved gases from escaping"],
    a=1, why="A large heat capacity means a large energy input produces a small temperature change, damping diurnal and seasonal extremes at planetary and cellular scales."),
  dict(q="A student argues that fire is alive because it grows, consumes fuel, produces waste, and responds to wind. The strongest scientific rebuttal is that fire",
    opts=["is too hot to contain molecules","has no bounded, self-maintained organisation with heritable information","does not consume oxygen","does not produce carbon dioxide"],
    a=1, why="Fire has no boundary it maintains, no internal information store, and no mechanism for heritable variation. The rebuttal has to target organisation and heredity, not superficial chemistry."),
  dict(q="Which statement about entropy and living systems is correct?",
    opts=["Living systems decrease the entropy of the universe","Living systems maintain internal order while increasing the entropy of their surroundings","Living systems are closed systems at equilibrium","Living systems are exempt from the second law"],
    a=1, why="Local order is paid for by exported heat and disordered waste. Total entropy still increases, which is why life requires a continuous energy flux."),
  dict(q="In designing a life-detection mission, the practical value of an operational definition of life is that it",
    opts=["settles the philosophical question of what life is","specifies measurable criteria and therefore what instruments must detect","guarantees that no false positives will occur","eliminates the need for control samples"],
    a=1, why="Operational definitions translate a concept into measurements. They do not settle the philosophy, and they make controls more necessary, not less, because each measurable criterion has abiotic mimics."),
 ],
 applied=[
  ("Build a two-column table of the standard criteria for life. In the left column, state the criterion; in the right, name one non-living system that satisfies it. Then write a 150-word paragraph identifying which combination of criteria you would require before reporting a detection, and what you would be prepared to miss by requiring it.",
   "Look for explicit acknowledgement of the trade-off between false positives and false negatives."),
  ("Choose one homeostatic variable in the human body (temperature, blood glucose, or blood pH). Draw the negative feedback loop with receptor, control centre, and effector labelled, then predict the failure mode if the receptor's sensitivity drops by half.",
   "The prediction should describe wider oscillation around the set point, not simply 'the system fails'."),
 ],
)

CONTENT["ch02"] = dict(
 bridge=("Every proposed biosignature instrument is really a bet about cells: that life compartmentalises, that it "
         "runs redox chemistry across a membrane, and that it leaves lipids behind. Cell biology is where those "
         "bets are justified or abandoned."),
 sections=[
  ("Two cell architectures", [
    "Prokaryotic cells (Bacteria and Archaea) lack a membrane-bound nucleus and membrane-bound organelles, carry a single circular chromosome in a nucleoid, and typically measure 0.5-5 micrometres. Eukaryotic cells are 10-100 micrometres, compartmentalise function into organelles, and package linear chromosomes with histones inside a nuclear envelope.",
    "Both share the plasma membrane, cytoplasm, ribosomes, and DNA. That shared core is the strongest cellular evidence for common ancestry. The differences matter for astrobiology because surface-to-volume constraints put an upper bound on how large an unstructured cell can be while still exchanging material by diffusion, and a lower bound on how small a cell can be and still hold a genome and its machinery."],
   ["nucleoid","organelle","surface-to-volume ratio","endosymbiosis"]),
  ("Membranes and transport", [
    "The fluid mosaic membrane is a phospholipid bilayer with embedded proteins. Small nonpolar molecules cross freely; ions and polar molecules require channels or carriers. Passive transport, including simple and facilitated diffusion and osmosis, follows the gradient and costs no ATP; active transport moves solutes against the gradient using ATP or a coupled ion gradient.",
    "The sodium-potassium pump is the classic case: three sodium ions out, two potassium ions in, one ATP consumed. The resulting gradients store energy that drives secondary active transport and, in neurons, the action potential. Archaeal membranes differ instructively: ether-linked, branched isoprenoid chains, sometimes fused into a monolayer, which is far more stable at high temperature and low pH."],
   ["fluid mosaic","facilitated diffusion","tonicity","electrochemical gradient"]),
  ("Energy capture", [
    "Cellular respiration oxidises glucose in glycolysis, pyruvate oxidation, the citric acid cycle, and oxidative phosphorylation, yielding roughly 30-32 ATP per glucose under aerobic conditions. The final step is chemiosmosis: the electron transport chain pumps protons across a membrane, and ATP synthase harvests the return flow.",
    "Photosynthesis reverses the direction of carbon flow, using light to drive electron transport, generate ATP and NADPH, and fix carbon dioxide in the Calvin cycle. The common mechanism is the point: both processes are proton gradients across membranes. Chemiosmosis is nearly universal on Earth, and any energy-harvesting system on another world faces the same problem of coupling a redox reaction to useful work."],
   ["chemiosmosis","ATP synthase","redox couple","autotroph"]),
  ("Cell division and continuity", [
    "Prokaryotes divide by binary fission. Eukaryotes run a cell cycle of interphase (G1, S, G2) and mitosis, with checkpoints that verify size, DNA integrity, and spindle attachment before division proceeds. Mitosis produces two genetically identical diploid cells for growth and repair.",
    "Meiosis instead halves the chromosome number across two divisions and generates variation through crossing over and independent assortment, producing four genetically distinct haploid gametes. Variation is not decoration: it is the raw material selection acts on, so the meiotic mechanism connects directly to the evolutionary criterion in the definition of life."],
   ["binary fission","checkpoint","crossing over","haploid"]),
 ],
 figure=dict(kind="flow", title="Energy flow through respiration",
   caption="Glucose is oxidised in stages; most ATP comes from the proton gradient at the end, not from the earlier substrate-level steps.",
   items=["Glucose","Glycolysis (2 ATP)","Pyruvate oxidation","Citric acid cycle","Electron transport + chemiosmosis (~26-28 ATP)"]),
 practice=[
  dict(q="A newly described cell is 0.4 micrometres across, has no nucleus, and has ether-linked branched membrane lipids. The most defensible initial classification is",
    opts=["a small eukaryote","an archaeon","a virus","a plant cell"],
    a=1, why="Ether-linked, branched isoprenoid lipids are diagnostic of Archaea. Bacteria use ester-linked straight-chain fatty acids; eukaryotes have nuclei; viruses are not cells."),
  dict(q="A cell is placed in a solution and swells. The solution is",
    opts=["hypertonic to the cytoplasm","hypotonic to the cytoplasm","isotonic to the cytoplasm","saturated with solute"],
    a=1, why="Water moves toward higher solute concentration. Swelling means water entered, so the external solution had lower solute concentration: it was hypotonic."),
  dict(q="Which finding would most strongly indicate active rather than passive transport?",
    opts=["Solute movement stops when temperature is lowered slightly","Solute accumulates inside against its concentration gradient and stops when ATP synthesis is blocked","Solute crosses faster than predicted for its size","Movement continues after the cell dies"],
    a=1, why="Accumulation against a gradient with ATP dependence is the defining pair. Faster-than-predicted movement suggests facilitated diffusion, which is still passive."),
  dict(q="Chemiosmosis is central to astrobiological thinking about metabolism because it shows that a cell can",
    opts=["make ATP without any membrane","convert a redox reaction into stored energy using an ion gradient across a membrane","survive without a genome","fix carbon without an energy source"],
    a=1, why="The mechanism generalises: any redox couple with a membrane and a pump can, in principle, store energy this way, which broadens the range of plausible energy sources beyond sunlight and organic fuel."),
  dict(q="Surface-to-volume ratio constrains cell size because as a cell grows, its",
    opts=["volume increases faster than its surface area, limiting exchange per unit of cytoplasm","surface area increases faster than volume, wasting membrane","density decreases, causing it to float","genome must be duplicated more often"],
    a=1, why="Volume scales with the cube of length while area scales with the square, so exchange capacity per unit volume falls as size increases."),
  dict(q="Crossing over during meiosis I contributes to which criterion in the definition of life?",
    opts=["Homeostasis","Heritable variation available to selection","Metabolism","Compartmentalisation"],
    a=1, why="Recombination generates new allele combinations, supplying the variation on which Darwinian evolution depends."),
  dict(q="Comparing an aerobic culture to the same organism grown without oxygen, the anaerobic culture consumes glucose faster. The best explanation is that",
    opts=["fermentation yields far less ATP per glucose, so more glucose is required for the same energy demand","anaerobic cells are larger","oxygen inhibits glycolysis","fermentation produces more ATP per glucose"],
    a=1, why="Fermentation yields about 2 ATP per glucose versus roughly 30 aerobically, so substrate consumption rises sharply to meet the same demand. This is the Pasteur effect."),
  dict(q="The mitochondrion's double membrane, circular DNA, and bacterial-type ribosomes are cited as evidence for",
    opts=["convergent evolution","endosymbiotic origin from a bacterial ancestor","abiogenesis inside eukaryotes","horizontal gene transfer from viruses"],
    a=1, why="These are the classic endosymbiosis lines of evidence, supported further by mitochondrial ribosome sensitivity to antibacterial antibiotics."),
  dict(q="A drug blocks the sodium-potassium pump. The most immediate consequence for a neuron is",
    opts=["loss of the ionic gradients that sustain the resting membrane potential","immediate rupture of the nuclear envelope","cessation of transcription","conversion of the cell to anaerobic metabolism"],
    a=1, why="The pump maintains the gradients; blocking it degrades the resting potential and secondary transport that depends on the sodium gradient."),
  dict(q="If lipid biomarkers are recovered from an ancient sediment, the strongest reason to treat them cautiously as a biosignature is that",
    opts=["lipids never survive in sediments","some lipid-like molecules can form abiotically and contamination is difficult to exclude","lipids are only produced by eukaryotes","lipids cannot be measured accurately"],
    a=1, why="Abiotic synthesis routes exist for simple lipids, and modern contamination is a persistent problem in ancient-sample work, so controls and contextual evidence carry the argument."),
 ],
 applied=[
  ("Draw an annotated comparison of a bacterial, archaeal, and eukaryotic cell, marking the features that would survive as detectable traces in a 100-million-year-old sediment and those that would not.",
   "Membrane lipids and mineralised structures persist; cytoplasmic organisation does not. Expect that distinction to be explicit."),
  ("Model the transport problem for a cell in a brine 5 times saltier than its cytoplasm. Describe two strategies for surviving it, one using compatible solutes and one using active ion export, and identify the metabolic cost of each.",
   "The answer should connect osmotic balance to ATP budget, which is the same trade-off halophiles face."),
 ],
)

CONTENT["ch03"] = dict(
 bridge=("The tree of life is the map astrobiology uses to say what 'life as we know it' includes. Its deepest "
         "branches are thermophilic and chemosynthetic, which is why the environments once dismissed as hostile "
         "are now the first places anyone looks."),
 sections=[
  ("Information flow and its errors", [
    "DNA stores information as base sequence; transcription copies a gene into RNA; translation reads codons at the ribosome to build a polypeptide. The genetic code is nearly universal and redundant, with 64 codons specifying 20 amino acids plus stop signals. Universality is itself a major biological observation: it argues for a single common ancestor rather than repeated independent origins.",
    "Mutations are changes in that sequence: substitutions, insertions, deletions, and larger rearrangements. Most are neutral or harmful, and a small fraction is beneficial in a given environment. Mutation supplies variation blindly; selection is what makes the outcome non-random."],
   ["codon","redundancy","point mutation","frameshift"]),
  ("Inheritance and populations", [
    "Mendelian ratios follow from segregation and independent assortment, but most traits of interest are polygenic and environmentally modulated. The population, not the individual, is the unit that evolves: allele frequencies shift under selection, drift, gene flow, and mutation.",
    "Hardy-Weinberg equilibrium describes the null case in which frequencies do not change, and its violation is how population genetics detects evolution in progress. Drift matters most in small populations, which is directly relevant to any isolated colony, terrestrial or otherwise."],
   ["allele frequency","genetic drift","gene flow","Hardy-Weinberg"]),
  ("Speciation and the shape of the tree", [
    "Natural selection requires variation, heritability, and differential reproductive success. Given reproductive isolation, whether geographic, temporal, behavioural, or genetic, populations diverge until gene flow ceases and speciation is complete.",
    "Phylogenies represent these splits. Shared derived characters group taxa; convergent similarity does not. Molecular phylogenetics, particularly ribosomal RNA comparison, restructured the tree in the late twentieth century and produced the three-domain system: Bacteria, Archaea, and Eukarya. Horizontal gene transfer complicates the picture in prokaryotes, making the deepest branches more of a network than a clean bifurcating tree."],
   ["clade","homology","analogy","horizontal gene transfer"]),
  ("Microorganisms and extremophiles", [
    "Prokaryotes dominate Earth's biomass diversity and metabolic range. They fix nitrogen, oxidise sulfur, reduce metals, respire nitrate and sulfate, and generate methane. That metabolic variety, not multicellular complexity, is what makes life plausible in dark, cold, or chemically hostile settings.",
    "Extremophiles are defined relative to human comfort: thermophiles and hyperthermophiles above 45 and 80 degrees Celsius, psychrophiles near freezing, halophiles in saturated brine, acidophiles and alkaliphiles at pH extremes, barophiles under crushing pressure, and radioresistant organisms such as Deinococcus radiodurans that reassemble shattered genomes. Each is an existence proof that widens the habitable envelope used in planetary assessment."],
   ["chemolithotroph","hyperthermophile","halophile","polyextremophile"]),
 ],
 figure=dict(kind="compare", title="Three domains of life",
   caption="Ribosomal RNA comparison split the prokaryotes into two domains. Archaea share transcription machinery with Eukarya but cell structure with Bacteria.",
   left=("Bacteria", ["Ester-linked, straight-chain lipids","Peptidoglycan cell wall","Single RNA polymerase","No introns in most genes"]),
   right=("Archaea", ["Ether-linked, branched lipids","No peptidoglycan","Eukaryote-like RNA polymerase","Dominant in many extreme habitats"])),
 practice=[
  dict(q="Two organisms share a streamlined body form but differ in every molecular character examined. The shared form is best interpreted as",
    opts=["homology indicating recent common ancestry","analogy produced by convergent evolution","evidence of horizontal gene transfer","a sampling artefact"],
    a=1, why="Similar selective pressures produce similar form independently. Only shared derived molecular and structural characters support common ancestry."),
  dict(q="The near-universality of the genetic code across all three domains is usually taken as evidence that",
    opts=["life arose many times independently with the same code","all known life descends from a common ancestor that already used this code","the code is chemically the only possible one","codes cannot change over time"],
    a=1, why="Independent origins would be unlikely to converge on the same arbitrary codon assignments; the parsimonious explanation is shared descent, though minor variant codes do exist."),
  dict(q="A small founding population on an isolated island shows allele frequencies very different from the mainland source, with no evidence of differential survival. The most likely mechanism is",
    opts=["natural selection","genetic drift through a founder effect","gene flow","directional mutation"],
    a=1, why="Random sampling of a small founding group shifts frequencies without any fitness difference. Absence of differential survival argues against selection."),
  dict(q="Deinococcus radiodurans survives radiation doses that shatter its chromosome primarily because it",
    opts=["has a radiation-proof cell wall","efficiently reassembles fragmented DNA using multiple genome copies","does not use DNA as its genetic material","enters a permanent dormant state"],
    a=1, why="Its resistance is repair-based: multiple genome copies and highly efficient reassembly, aided by manganese-based protection of repair proteins."),
  dict(q="Why do hyperthermophiles occupy positions of special interest near the base of rRNA trees?",
    opts=["They are the largest organisms known","Their placement is consistent with a hot early environment for the last universal common ancestor","They have the smallest genomes","They cannot exchange genes"],
    a=1, why="Deep branching of thermophilic lineages is one line of argument for a thermophilic LUCA, though it remains contested and may reflect tree-construction artefacts."),
  dict(q="Horizontal gene transfer complicates deep phylogeny because it",
    opts=["prevents mutation from occurring","moves genes between lineages, so different genes can yield different trees","eliminates all sequence variation","only occurs in eukaryotes"],
    a=1, why="Different genes with different transfer histories give conflicting topologies, which is why the deep tree is better modelled as a network in prokaryotes."),
  dict(q="A chemolithoautotroph in a subsurface aquifer with no sunlight most plausibly obtains energy and carbon from",
    opts=["light and organic matter","oxidation of inorganic compounds such as hydrogen or sulfide, with carbon from CO2","photosynthesis using infrared light","consumption of other cells only"],
    a=1, why="Chemolithoautotrophy uses inorganic electron donors and inorganic carbon, which is the metabolic model most often invoked for subsurface Mars or Europa's ocean."),
  dict(q="In binomial nomenclature, Halobacterium salinarum places the organism in",
    opts=["genus Halobacterium, species salinarum","family Halobacterium, genus salinarum","domain Halobacterium, kingdom salinarum","order Halobacterium, class salinarum"],
    a=0, why="The first term is the genus and the second the specific epithet; together they name the species. Note also that despite the name, Halobacterium is an archaeon."),
  dict(q="A frameshift mutation is usually more damaging than a single substitution because it",
    opts=["changes one amino acid at a critical site","alters the reading frame, changing all downstream codons","always deletes an entire gene","prevents transcription from starting"],
    a=1, why="Insertion or deletion of a number of bases not divisible by three shifts the frame, typically producing a garbled sequence and a premature stop."),
  dict(q="Which finding would most weaken the claim that a sample from a Martian brine contains life related to Earth life?",
    opts=["The sample contains amino acids","The amino acids are racemic and the set differs from the 20 used by terrestrial life","The sample contains carbon","The sample was collected from a subsurface layer"],
    a=1, why="A racemic mixture and a non-terrestrial amino acid inventory argue against both terrestrial contamination and shared ancestry. It would suggest either abiotic chemistry or a genuinely independent origin."),
 ],
 applied=[
  ("Given a matrix of five taxa and six characters, construct the most parsimonious cladogram and mark which characters are shared derived and which are convergent. State the assumption parsimony makes and one situation where it misleads.",
   "Parsimony assumes evolutionary change is rare; long-branch attraction is the standard counterexample."),
  ("Select one extremophile group and write a one-page case for the specific planetary environment it makes plausible. Cite the physiological mechanism, not just the tolerance range.",
   "The mechanism, such as compatible solutes or DNA repair capacity, is what transfers to another world; the tolerance number alone does not."),
 ],
)

CONTENT["ch04"] = dict(
 bridge=("Any long-duration crewed mission is a plant biology problem. Crops must fix carbon, recycle water, and "
         "regenerate atmosphere in a sealed volume, which is why every closed-ecosystem design begins with the "
         "physiology in this chapter."),
 sections=[
  ("Plant diversity and the terrestrial problem", [
    "Land plants solved a series of problems in sequence: desiccation, structural support without buoyancy, gamete transfer without water, and gas exchange without losing too much water. Bryophytes remain small and moisture-dependent; ferns added vascular tissue; gymnosperms added seeds and pollen; angiosperms added flowers, fruit, and double fertilisation.",
    "The cuticle, stomata, lignified vascular tissue, and seeds are the key innovations. Each is a trade-off. A cuticle prevents water loss but blocks gas exchange, so stomata are needed; stomata permit exchange but leak water, so they must be regulated."],
   ["cuticle","xylem","phloem","alternation of generations"]),
  ("Tissues, organs, and transport", [
    "Roots anchor and absorb; stems support and transport; leaves capture light and exchange gases. Xylem carries water and minerals upward through dead, lignified conduits; phloem carries sugars in living sieve tubes under pressure.",
    "The cohesion-tension mechanism explains upward water movement without a pump: evaporation from leaf surfaces creates negative pressure, and hydrogen bonding transmits that tension continuously to the roots. This is a purely physical mechanism dependent on water's properties, and it fails under altered gravity or reduced pressure, which is why microgravity plant experiments focus so heavily on root-zone water delivery."],
   ["cohesion-tension","transpiration","translocation","stomatal conductance"]),
  ("Photosynthesis in context", [
    "Light reactions in thylakoid membranes split water, release oxygen, and generate ATP and NADPH; the Calvin cycle fixes carbon dioxide into sugars in the stroma. Rubisco, the fixing enzyme, also reacts with oxygen, and this photorespiration wastes energy under hot, dry conditions when stomata close.",
    "C4 and CAM pathways are the evolutionary responses: C4 plants concentrate carbon dioxide spatially, CAM plants temporally by fixing at night. For controlled-environment agriculture, the practical lever is different: light spectrum and intensity, carbon dioxide enrichment, and root-zone conditions can be tuned directly, which is why crop selection for space habitats favours short, fast, high-harvest-index species."],
   ["photorespiration","rubisco","C4 pathway","harvest index"]),
  ("Growth responses and adaptation", [
    "Tropisms are directional growth responses: phototropism toward light mediated by auxin redistribution, gravitropism guided by statoliths settling in specialised cells, and thigmotropism to touch. Hormones including auxin, gibberellin, cytokinin, abscisic acid, and ethylene coordinate germination, elongation, dormancy, and senescence.",
    "In microgravity, gravitropic cues vanish and phototropic and hydrotropic cues dominate. Experiments aboard orbital laboratories show that plants still complete life cycles, but with altered root architecture, modified gene expression, and problems in water and gas boundary layers, since convection is weak without buoyancy-driven flow."],
   ["auxin","statolith","gravitropism","boundary layer"]),
 ],
 figure=dict(kind="flow", title="The transpiration stream",
   caption="Water moves along a continuous tension gradient from soil to atmosphere. No metabolic pump is involved, which makes the mechanism sensitive to changes in gravity and pressure.",
   items=["Soil water","Root hairs","Xylem (cohesion-tension)","Leaf mesophyll","Stomata to atmosphere"]),
 practice=[
  dict(q="Water rises in a tall tree without a pump primarily because",
    opts=["root pressure pushes it up the entire height","transpiration generates tension transmitted through cohesive water columns in xylem","phloem actively transports water upward","capillary action alone lifts water to the crown"],
    a=1, why="Cohesion-tension is the accepted mechanism. Root pressure and capillarity contribute but cannot account for heights of tens of metres."),
  dict(q="A crop chamber in a habitat shows leaf overheating and reduced photosynthesis despite adequate light and water. The most likely cause specific to the microgravity environment is",
    opts=["excess gravity compressing the leaves","weak convection producing thick boundary layers that trap heat and humidity","complete absence of transpiration","inability of chlorophyll to absorb light"],
    a=1, why="Without buoyancy-driven convection, still air forms thick boundary layers around leaves, impeding heat and gas exchange. Forced airflow is the standard countermeasure."),
  dict(q="Photorespiration reduces yield because rubisco",
    opts=["binds oxygen instead of carbon dioxide, consuming energy without net fixation","stops functioning above 20 degrees Celsius","releases carbon dioxide only at night","cannot bind carbon dioxide at all"],
    a=1, why="Rubisco's oxygenase activity produces a compound that must be salvaged at ATP cost, releasing previously fixed carbon."),
  dict(q="CAM plants open stomata at night mainly to",
    opts=["capture moonlight for photosynthesis","reduce water loss while still acquiring carbon dioxide","increase transpiration for cooling","avoid herbivores"],
    a=1, why="Night opening exploits cooler, more humid conditions, lowering transpiration per unit of carbon fixed. Carbon is stored as an organic acid and released to the Calvin cycle by day."),
  dict(q="Gravitropism in roots depends on",
    opts=["auxin destruction in the root cap","sedimentation of dense statoliths that triggers asymmetric auxin distribution","direct detection of magnetic fields","phloem pressure differentials"],
    a=1, why="Amyloplasts acting as statoliths settle in columella cells, biasing auxin transport and causing differential elongation."),
  dict(q="For a bioregenerative life-support system, the most important plant trait among the following is",
    opts=["maximum plant height","high harvest index with short life cycle in controlled conditions","large seed size","deep taproot development"],
    a=1, why="Edible mass per unit of input and time governs system performance in a mass- and volume-constrained habitat."),
  dict(q="Closing stomata during drought is regulated primarily by",
    opts=["ethylene","abscisic acid","gibberellin","cytokinin"],
    a=1, why="Abscisic acid accumulates under water stress and triggers guard-cell ion efflux, causing closure."),
  dict(q="Which pairing of structure and function is correct?",
    opts=["Xylem transports sugars in living cells","Phloem transports sugars under pressure in living sieve tubes","Cuticle enables gas exchange","Stomata provide structural support"],
    a=1, why="Phloem translocation follows the pressure-flow model in living sieve tube elements; xylem conduits are dead at maturity and carry water."),
  dict(q="A plant grown under red light only develops elongated, spindly stems. The best explanation involves",
    opts=["absence of blue light cues that normally restrain elongation","excess carbon dioxide","insufficient nitrogen","gravitropic failure"],
    a=1, why="Blue light photoreceptors suppress stem elongation and drive normal morphology; spectrum design is therefore a real engineering variable in habitat agriculture."),
  dict(q="The strongest argument for including plants rather than only stored food on a multi-year mission is that plants",
    opts=["are lighter than any stored food","regenerate atmosphere and water while producing food, closing several loops at once","eliminate the need for waste processing","require no crew time"],
    a=1, why="The case rests on loop closure across oxygen, water, and food, offsetting the substantial mass, power, and crew-time costs plants impose."),
 ],
 applied=[
  ("Design a 10 square metre crop module for a six-person habitat. Specify three crops, light spectrum and photoperiod, carbon dioxide setpoint, and the airflow needed to manage boundary layers. State the assumptions you cannot verify and how you would test them.",
   "The unverifiable assumptions matter more than the numbers here; look for explicit flagging."),
  ("Compare the water transport problem on Earth and in microgravity. Explain why cohesion-tension does not simply stop, and identify what actually fails in the root zone.",
   "Capillarity and surface tension persist; what fails is drainage, air-water separation, and gas exchange at the roots."),
 ],
)

CONTENT["ch05"] = dict(
 bridge=("Comparative zoology is a catalogue of solutions to problems every organism faces anywhere: acquire energy, "
         "exchange gases, move, regulate the internal environment, and reproduce. Reading it as a solution set, rather "
         "than a taxonomy, is what makes it transferable to hypothetical biospheres."),
 sections=[
  ("Body plans as engineering choices", [
    "Animal body plans vary along a few axes: symmetry (radial or bilateral), germ layers (diploblastic or triploblastic), body cavity (acoelomate, pseudocoelomate, coelomate), segmentation, and developmental pattern (protostome or deuterostome). Bilateral symmetry with cephalisation concentrates sensory tissue at the leading end, which is the foundation of directed movement and rapid response.",
    "A coelom permits organs to move independently of the body wall and supports a hydrostatic skeleton. Segmentation allows repeated units to be modified for different functions. These are not arbitrary distinctions: each configuration constrains size, mobility, and the kinds of organ systems that can be supported."],
   ["cephalisation","coelom","segmentation","protostome"]),
  ("Comparative organ systems", [
    "Gas exchange solutions scale with body size and medium: diffusion across the surface in small or flat organisms, gills in water, tracheae delivering air directly to tissues in insects, and lungs with ventilation in vertebrates. Circulatory systems are open or closed, with progressively separated pulmonary and systemic circuits in the vertebrate series.",
    "Excretion balances nitrogen disposal against water cost: ammonia is cheap but requires abundant water, urea is intermediate, uric acid is expensive but water-conserving and suited to eggs and dry habitats. This trio is a compact illustration of environmental physics driving biochemistry, which is exactly the reasoning applied when speculating about life under different water availability."],
   ["countercurrent exchange","open circulation","osmoregulation","ureotelic"]),
  ("Reproduction, development, and behaviour", [
    "Reproductive strategies range across asexual and sexual modes, external and internal fertilisation, and oviparity to viviparity, with a trade-off between offspring number and parental investment. Development proceeds through cleavage, gastrulation, and organogenesis under conserved regulatory genes such as the Hox cluster.",
    "Behaviour spans innate fixed action patterns through associative learning to social organisation and communication. Behaviour is a phenotype under selection, and it is measurable: reaction time, orientation, and choice experiments produce quantitative data suitable for the analysis skills this course builds."],
   ["Hox genes","r/K strategy","fixed action pattern","phenotypic plasticity"]),
  ("Ecological relationships", [
    "Populations interact through competition, predation, parasitism, mutualism, and commensalism, and energy moves through trophic levels with roughly 10 per cent transfer efficiency. That inefficiency is why food chains are short and why closed habitats are usually designed with very few trophic levels.",
    "Communities and ecosystems have properties, including productivity, stability, and nutrient cycling, that no single population has. In a sealed habitat these become engineering variables: cycle rates, buffer capacity, and redundancy determine whether the system survives a perturbation, and the ecological literature on stability is the closest available guide."],
   ["trophic efficiency","keystone species","nutrient cycling","resilience"]),
 ],
 figure=dict(kind="compare", title="Two developmental lineages",
   caption="Cleavage pattern and the fate of the blastopore define the deepest split among bilaterian animals.",
   left=("Protostomes", ["Spiral, determinate cleavage","Blastopore becomes the mouth","Includes annelids, molluscs, arthropods","Coelom from splitting mesoderm"]),
   right=("Deuterostomes", ["Radial, indeterminate cleavage","Blastopore becomes the anus","Includes echinoderms, chordates","Coelom from mesodermal pouches"])),
 practice=[
  dict(q="Cephalisation is functionally significant because it",
    opts=["increases body size","concentrates sensory and neural tissue at the leading end, supporting directed movement","reduces energy expenditure in digestion","enables asexual reproduction"],
    a=1, why="Sensory concentration at the end that meets the environment first shortens response latency for a mobile bilaterian."),
  dict(q="An animal in a dry habitat that lays shelled eggs most likely excretes nitrogen as",
    opts=["ammonia","uric acid","nitrogen gas","nitrate"],
    a=1, why="Uric acid is nearly insoluble and can be stored in an egg without toxicity or water cost, though its synthesis is energetically expensive."),
  dict(q="Countercurrent exchange in fish gills increases oxygen uptake because",
    opts=["it warms the blood before exchange","a favourable gradient is maintained along the entire exchange surface","it reverses the direction of diffusion","it eliminates the need for haemoglobin"],
    a=1, why="Opposing flow keeps the partial-pressure difference positive across the whole length, unlike concurrent flow which equilibrates halfway."),
  dict(q="Roughly 10 per cent energy transfer between trophic levels implies that a closed habitat should",
    opts=["include many trophic levels for stability","minimise trophic levels between producers and humans","avoid producers entirely","rely on carnivores for efficiency"],
    a=1, why="Each additional level discards about 90 per cent of the energy, so short chains maximise usable output per unit of light and volume."),
  dict(q="Two species with nearly identical resource requirements coexist in the same habitat. The most likely explanation is",
    opts=["competitive exclusion has failed to operate at all","resource partitioning along an axis not yet measured","one species has become a producer","they have merged into one population"],
    a=1, why="Coexistence usually indicates niche differences on some dimension, spatial, temporal, or in resource size, that the observer has not yet identified."),
  dict(q="Hox genes are notable in comparative zoology because they",
    opts=["differ completely between phyla","are conserved regulators whose expression order corresponds to body-axis position","control only limb colour","are found only in vertebrates"],
    a=1, why="Their conservation and colinear expression demonstrate a shared developmental toolkit underlying very different body plans."),
  dict(q="An open circulatory system is generally associated with",
    opts=["high-pressure, high-flow delivery supporting sustained high metabolic rate","lower pressure and slower delivery, adequate for many invertebrates","the absence of any circulatory fluid","direct gas exchange only in vertebrates"],
    a=1, why="Haemolymph bathing tissues at low pressure limits delivery rate, which is one reason large, highly active animals tend to have closed systems."),
  dict(q="A species producing many offspring with no parental care in an unpredictable environment illustrates",
    opts=["K-selected strategy","r-selected strategy","obligate mutualism","kin selection"],
    a=1, why="High reproductive output with low per-offspring investment is favoured where mortality is high and unpredictable."),
  dict(q="Which measurement would best distinguish innate from learned behaviour in a laboratory activity?",
    opts=["Measuring the behaviour once in adults","Comparing the response of individuals reared with and without prior exposure to the stimulus","Measuring body mass across the group","Recording the behaviour at different times of day"],
    a=1, why="Deprivation or naive-rearing designs isolate whether experience is required for the response to appear."),
  dict(q="Applying comparative zoology to hypothetical extraterrestrial biospheres is most defensible when the argument is framed as",
    opts=["a prediction of specific alien anatomy","a set of physical constraints that any organism in that medium and gravity would face","proof that convergent evolution must occur","evidence that life must be carbon-based"],
    a=1, why="Physics constrains solutions; specific anatomy does not transfer. Framing the argument as constraints keeps it testable and avoids unfounded prediction."),
 ],
 applied=[
  ("Build a comparative matrix of five animal groups across gas exchange, circulation, excretion, support, and reproduction. Add a final column stating the environmental variable that best explains each group's solution.",
   "The final column is the analytical work; the first five are recall."),
  ("Term 1 synthesis: in 300 words, state the operational definition of life you would use for a life-detection mission, drawing on Weeks 1-5. Identify one criterion you deliberately excluded and defend the exclusion.",
   "This links directly to the Term 1 examination and to Week 11's evidence-ranking exercise."),
 ],
)
