# -*- coding: utf-8 -*-
CONTENT = {}

CONTENT["ch11"] = dict(
 bridge=("Term 3 turns the question around. Terms 1 and 2 described life as it is; from here the course asks which of "
         "those features are necessary, which are accidents of one planet's history, and how anyone could tell the "
         "difference from a distance."),
 sections=[
  ("The questions astrobiology actually asks", [
    "Astrobiology organises around three questions: how life begins and evolves, whether life exists elsewhere, and what the future of life is on Earth and beyond. It is a synthesis discipline, drawing on astronomy, planetary science, geology, chemistry, and biology, and its characteristic difficulty is that it must reason from a single confirmed example.",
    "That sample size of one is the central epistemic problem. Every generalisation about life risks mistaking a contingent feature of terrestrial biochemistry for a universal requirement. The discipline manages this by separating requirements that follow from physics and chemistry, such as an energy gradient and a solvent, from those that merely describe Earth life, such as DNA and the specific set of 20 amino acids."],
   ["sample size of one","contingency","universality","biosignature"]),
  ("Cosmic and geological setting", [
    "The biogenic elements have a stellar history: hydrogen from primordial nucleosynthesis, carbon, nitrogen, and oxygen from stellar fusion and asymptotic giant branch stars, heavier elements from supernovae and neutron star mergers. Molecular clouds contain a rich inventory of organic molecules, and carbonaceous meteorites such as Murchison carry amino acids, sugars, and nucleobases, showing that complex organic chemistry precedes planets.",
    "Early Earth, roughly 4.5 to 4.0 billion years ago, was hot, frequently impacted, and had an atmosphere dominated by carbon dioxide, nitrogen, and water vapour rather than the strongly reducing mixture originally assumed. Liquid water existed by at least 4.3 billion years ago on zircon evidence, and the oldest widely accepted biosignatures, carbon isotope ratios and stromatolite-like structures, appear between roughly 3.8 and 3.5 billion years ago."],
   ["CHNOPS","carbonaceous chondrite","Hadean","stromatolite"]),
  ("Origin-of-life hypotheses", [
    "Miller-Urey demonstrated that amino acids form abiotically from simple gases and an energy source, though under a more reducing atmosphere than early Earth likely had. Later work shows comparable yields from volcanic gas mixtures, impact chemistry, and delivery from space, so the availability of monomers is no longer the hard problem.",
    "The hard problems are polymerisation in water, compartmentalisation, and the emergence of heredity. The RNA world hypothesis proposes RNA as both catalyst and information carrier, supported by ribozymes and by the RNA core of the ribosome. Alkaline hydrothermal vent models emphasise natural proton gradients across mineral membranes as a precursor to chemiosmosis; surface pond models emphasise wet-dry cycling that drives polymerisation. Metabolism-first and genetics-first framings differ on which came first, and the evidence does not yet decide between them."],
   ["RNA world","ribozyme","protocell","abiogenesis"]),
  ("Habitability as an operational concept", [
    "Habitability is a property of an environment, not of an organism, and it is conditional on the kind of life assumed. The standard criteria are a solvent, an energy source with an exploitable gradient, the biogenic elements, and physicochemical conditions stable enough for long enough.",
    "Making this operational means committing to measurable proxies: surface or subsurface liquid water, redox couples, detectable C, H, N, O, P, S, and a stability timescale inferred from geology and orbital dynamics. Habitable does not mean inhabited, and uninhabited habitable environments are scientifically interesting in their own right because they constrain how often life arises given the opportunity."],
   ["habitability","redox couple","inhabited","continuously habitable zone"]),
 ],
 figure=dict(kind="flow", title="From stellar elements to a first cell",
   caption="Each arrow is a research problem, not a solved transition. Monomer availability is well supported; polymerisation, compartmentalisation, and heredity remain open.",
   items=["Elements from stars","Organics in clouds and meteorites","Prebiotic monomers on early Earth","Polymers and compartments","Heredity and selection (LUCA)"]),
 practice=[
  dict(q="The core epistemic problem of astrobiology is that",
    opts=["instruments are not sensitive enough","all inference rests on a single confirmed example of life","space is too large to survey","biology cannot be quantified"],
    a=1, why="With N equal to one, distinguishing necessary features of life from contingent features of terrestrial life is not empirically resolvable from within the sample."),
  dict(q="The Miller-Urey experiment is best described today as demonstrating that",
    opts=["life can be created in a laboratory","organic monomers form readily from simple molecules and an energy source","early Earth had a strongly reducing atmosphere","RNA preceded proteins"],
    a=1, why="It established monomer availability. The atmospheric assumption has been revised, and no step toward heredity or compartmentalisation was demonstrated."),
  dict(q="Amino acids in the Murchison meteorite are considered extraterrestrial in origin rather than contamination mainly because",
    opts=["they are present in high concentration","they include non-protein amino acids and show near-racemic mixtures unlike terrestrial biology","they were found inside a museum","they are identical to human proteins"],
    a=1, why="Terrestrial biology uses a specific set of 20 amino acids and almost exclusively the L form. Non-protein amino acids and near-racemic ratios point away from contamination."),
  dict(q="Support for the RNA world hypothesis includes",
    opts=["the discovery that ribosomal catalysis is performed by RNA","the fact that DNA is more stable than RNA","the absence of ribozymes in modern cells","the observation that proteins can self-replicate"],
    a=0, why="The ribosome's peptidyl transferase centre is a ribozyme, which suggests RNA catalysis is ancestral. DNA's greater stability is why it later took over information storage."),
  dict(q="Alkaline hydrothermal vent models are attractive to origins researchers principally because they provide",
    opts=["high ultraviolet flux for photochemistry","natural proton gradients across mineral compartments, prefiguring chemiosmosis","complete absence of water","abundant free oxygen"],
    a=1, why="The model supplies a compartment and a pre-existing gradient, addressing energy coupling and containment simultaneously."),
  dict(q="Wet-dry cycling in surface ponds is invoked to solve which specific problem?",
    opts=["Delivery of monomers from space","Polymerisation, which is thermodynamically unfavourable in bulk water","Radiation shielding","Element availability"],
    a=1, why="Condensation reactions release water, so bulk water opposes them. Evaporation shifts the equilibrium and drives chain formation."),
  dict(q="A planet is described as habitable but uninhabited. This statement is",
    opts=["self-contradictory","coherent, because habitability describes environmental conditions rather than the presence of life","only possible for gas giants","equivalent to saying life was destroyed"],
    a=1, why="Habitability is a property of the environment. Uninhabited habitable environments are a key test of how readily life arises."),
  dict(q="Which of the following is best classified as a requirement derived from physics and chemistry rather than an accident of terrestrial biology?",
    opts=["Use of DNA for information storage","Use of the standard 20 amino acids","An accessible energy gradient to sustain disequilibrium","Use of ATP as an energy currency"],
    a=2, why="Sustaining order requires a usable free-energy gradient in any chemistry. The other three are specific terrestrial implementations."),
  dict(q="Zircon evidence for liquid water by about 4.3 billion years ago is significant because it",
    opts=["proves life existed by that time","narrows the window between habitable conditions and the earliest biosignatures","shows the Hadean was cool everywhere","dates the origin of photosynthesis"],
    a=1, why="It compresses the time available for abiogenesis, implying that the transition may have been comparatively rapid once conditions allowed."),
  dict(q="Ranking origin-of-life hypotheses by evidence quality requires distinguishing",
    opts=["popular from unpopular hypotheses","laboratory demonstrations of a step, geological evidence of conditions, and untested plausibility arguments","published from unpublished work","chemistry from biology"],
    a=1, why="Evidence type, not conclusion, is the ranking axis. This distinction is the graded skill in this week's evidence-ranking exercise."),
 ],
 applied=[
  ("Notebook Entry 1: rank four origin-of-life hypotheses using an explicit evidence rubric with three tiers: demonstrated experimentally, consistent with geological evidence, plausible but untested. State what observation would move each hypothesis up or down a tier.",
   "The falsification condition is what distinguishes analysis from summary here."),
  ("Write an operational definition of habitability in fewer than 120 words, listing four measurable proxies and the instrument or observation that would supply each. Identify which proxy is hardest to measure remotely and why.",
   "Energy gradients are typically the hardest to establish remotely; look for that recognition or a defended alternative."),
 ],
)

CONTENT["ch12"] = dict(
 bridge=("Comparative planetology is habitability made concrete. The same five criteria applied to Mars, Europa, "
         "Enceladus, Titan, and Venus produce five very different verdicts, and the differences are what a habitability "
         "matrix is built to expose."),
 sections=[
  ("The habitable zone and its limits", [
    "The circumstellar habitable zone is the orbital range where a rocky planet with a suitable atmosphere could sustain surface liquid water. Its boundaries depend on stellar luminosity, atmospheric composition, and albedo, and they migrate outward as stars brighten with age, which gives rise to the continuously habitable zone.",
    "The concept has real limitations. It concerns surface water only, so it excludes subsurface oceans; it assumes an atmosphere; and it ignores tidal heating, which is precisely what makes the outer solar system interesting. Around M dwarfs the zone lies close in, where tidal locking, flares, and extreme ultraviolet erosion of atmospheres complicate matters, though such stars dominate the galaxy by number and are the easiest targets for transit spectroscopy."],
   ["habitable zone","tidal locking","albedo","tidal heating"]),
  ("Mars and Venus: two divergent histories", [
    "Mars preserves abundant evidence of past surface water: valley networks, deltas, hydrated clays and sulfates, and in situ sedimentary structures examined by rovers. Its loss of a global magnetic field and low gravity allowed atmospheric escape, leaving a thin carbon dioxide atmosphere with surface pressure near 6 millibars, below the triple point for stable liquid water. Present interest centres on the subsurface, where temperature and pressure permit brines and where radiation shielding is adequate.",
    "Venus is the opposite case: similar size and bulk composition, but a runaway greenhouse producing a surface near 460 degrees Celsius under 92 bars. Its cloud decks at 50 to 60 kilometres have Earth-like temperature and pressure, which is why the contested phosphine reports drew such attention. The scientific handling of that episode, claim, reanalysis, disputed detection, is itself a case study in biosignature standards."],
   ["atmospheric escape","runaway greenhouse","brine","triple point"]),
  ("Ocean worlds and Titan", [
    "Europa, Enceladus, Ganymede, and Titan host subsurface liquid layers maintained by tidal heating rather than sunlight. Enceladus vents plume material sampled directly by Cassini, containing water, salts, silica particles consistent with hydrothermal activity, methane, and complex organics. Europa's ice shell overlies a salty ocean likely in contact with a rocky seafloor, offering the chemical disequilibria that chemolithotrophy would require.",
    "Titan is different in kind. It has a dense nitrogen atmosphere, surface lakes of liquid methane and ethane, an active organic haze chemistry, and a probable subsurface water ocean. It is the only place where two candidate solvents are available, making it the strongest test case for whether the water requirement is a requirement of life or of the only life we know."],
   ["cryovolcanism","plume sampling","subsurface ocean","alternative solvent"]),
  ("Exoplanets and Earth analogues", [
    "More than five thousand exoplanets are confirmed, detected mainly by transit and radial velocity methods, with direct imaging and microlensing contributing. Transit spectroscopy retrieves atmospheric composition, and space-based infrared observation has begun characterising the atmospheres of small planets, though results for terrestrial planets around M dwarfs so far indicate thin or absent atmospheres in several well-studied cases.",
    "Terrestrial analogue sites, including the Atacama, Rio Tinto, Antarctic dry valleys, deep-sea vents, and Philippine hypersaline and hydrothermal settings, do parallel work. They provide the ground truth against which instruments and detection thresholds are calibrated, and they are where extremophile physiology is studied under conditions that can be manipulated."],
   ["transit spectroscopy","radial velocity","analogue site","detection threshold"]),
 ],
 figure=dict(kind="scale", title="Where liquid water is plausible",
   caption="Surface habitability tracks distance from the Sun; subsurface habitability does not. Tidal heating decouples the outer worlds from the classical habitable zone entirely.",
   items=[("Venus","Surface 460 C; clouds temperate"),("Earth","Surface ocean; the reference case"),("Mars","Past surface water; present subsurface brine"),("Europa","Ice shell over salty ocean; tidal heating"),("Enceladus","Vented plume sampled directly"),("Titan","Methane lakes plus deep water ocean")]),
 practice=[
  dict(q="The classical habitable zone concept excludes Europa and Enceladus because it is defined in terms of",
    opts=["planetary mass","surface liquid water sustained by stellar flux","magnetic field strength","atmospheric oxygen"],
    a=1, why="Tidally heated subsurface oceans are independent of stellar flux, so the classical zone misses them entirely."),
  dict(q="Liquid water is unstable on most of the Martian surface today primarily because",
    opts=["temperatures never rise above freezing anywhere","atmospheric pressure is below the triple point of water over most of the surface","there is no water on Mars","the soil is chemically inert"],
    a=1, why="At about 6 millibars, water sublimes or boils rather than persisting as a liquid, though salty brines can be locally stable."),
  dict(q="Mars lost most of its atmosphere largely because it",
    opts=["has no gravity at all","lost its global magnetic field and has low gravity, permitting solar-wind stripping and thermal escape","was struck by a single large impact","absorbed its atmosphere into the crust entirely"],
    a=1, why="MAVEN measurements support ongoing solar-wind-driven escape, accelerated after the dynamo shut down early in Martian history."),
  dict(q="Silica nanoparticles and molecular hydrogen in the Enceladus plume are significant because they suggest",
    opts=["photosynthesis in the plume","hydrothermal water-rock interaction at the ocean floor, providing chemical energy","the ocean is frozen solid","the moon has an oxygen atmosphere"],
    a=1, why="Both are products of high-temperature water-rock reactions, indicating a seafloor energy source usable by chemolithotrophs."),
  dict(q="Titan is described as the strongest test of the water requirement because it",
    opts=["has no liquids at all","offers both hydrocarbon surface liquids and a probable subsurface water ocean","is the same temperature as Earth","orbits inside the habitable zone"],
    a=1, why="Two candidate solvents in one body allow the water assumption to be tested rather than assumed."),
  dict(q="A planet in the habitable zone of an M dwarf faces which specific additional risk?",
    opts=["Excessive stellar mass loss into the planet","Flare activity and extreme ultraviolet flux that can erode the atmosphere, plus likely tidal locking","Complete absence of a habitable zone","Orbital periods too long to observe"],
    a=1, why="Close-in orbits bring stronger high-energy flux and tidal effects; several observed cases suggest thin or absent atmospheres."),
  dict(q="Venus's cloud layer at 50 to 60 km attracts attention because",
    opts=["it contains liquid water droplets","its temperature and pressure are near Earth-surface values despite the hostile surface","it is chemically inert","it rotates with the surface"],
    a=1, why="Temperate conditions in an otherwise extreme environment define the only plausible present-day Venusian habitable niche, albeit an extremely acidic one."),
  dict(q="In a habitability matrix, assigning weights to criteria requires the analyst to",
    opts=["treat all criteria as equally important by default","state and justify the assumed type of life, because the weighting follows from it","exclude energy from the assessment","rank worlds by distance from Earth"],
    a=1, why="Weights encode assumptions. A matrix built for photosynthetic surface life ranks worlds differently from one built for subsurface chemolithotrophy."),
  dict(q="Transit spectroscopy determines atmospheric composition by measuring",
    opts=["the reflected visible colour of the planet","wavelength-dependent absorption as starlight passes through the planet's atmosphere during transit","the planet's radial velocity","the planet's magnetic field"],
    a=1, why="Absorption features imprinted on the transmitted starlight reveal molecular species, though the signal is small and demands careful systematics control."),
  dict(q="Terrestrial analogue sites are scientifically valuable mainly because they",
    opts=["prove that life exists elsewhere","allow instruments, thresholds, and sampling protocols to be tested against known ground truth","are cheaper than missions and therefore sufficient","reproduce extraterrestrial conditions exactly"],
    a=1, why="Their value is calibration and protocol development under conditions that can be manipulated and independently verified."),
 ],
 applied=[
  ("Notebook Entry 2: build a habitability matrix for Mars, Europa, Enceladus, Titan, and Venus across solvent, energy, elements, stability, and accessibility. Assign explicit weights, state the assumed life type, and rank the worlds. Then re-run it with a different assumed life type and report what changed.",
   "The re-run is the analytical payload: it shows the ranking is a function of assumptions, not of the worlds alone."),
  ("Select one Philippine field site (hypersaline, hydrothermal, or high-altitude) and argue in 300 words for its use as a planetary analogue. Specify the parameter it reproduces and the parameter it fails to reproduce.",
   "The failure statement matters as much as the match; no terrestrial site reproduces radiation and gravity together."),
 ],
)

CONTENT["ch13"] = dict(
 bridge=("This is the methodological heart of the course. A biosignature claim is only as strong as the abiotic "
         "explanations it survives and the contamination controls it can document, which is why life detection is a "
         "problem of experimental design before it is a problem of instrumentation."),
 sections=[
  ("Categories of biosignature", [
    "Biosignatures fall into recognisable classes. Morphological signatures are structures such as microfossils or stromatolites; chemical signatures include specific molecules such as membrane lipids and pigment biomarkers; isotopic signatures exploit the kinetic preference of enzymes for lighter isotopes, giving depleted carbon-13 in organic matter; chirality signatures use the strong enantiomeric excess biology maintains against racemisation.",
    "Atmospheric signatures are the class most relevant to exoplanets: a persistent disequilibrium mixture, oxygen with methane being the standard example, is difficult to sustain abiotically. Technosignatures, including narrowband radio emission, industrial gases, and anomalous thermal emission, form a separate category with the advantage of specificity and the disadvantage of assuming a particular developmental path."],
   ["isotopic fractionation","enantiomeric excess","atmospheric disequilibrium","technosignature"]),
  ("Abiotic mimics and false positives", [
    "Every class has mimics. Mineral structures such as biomorphs reproduce microfossil morphology convincingly; abiotic organic synthesis produces amino acids and lipid-like molecules; isotopic fractionation occurs in purely physical processes; and photochemical oxygen build-up on a water-rich planet losing hydrogen can produce oxygen with no biology at all.",
    "The Allan Hills 84001 episode is the canonical case. Claims of Martian nanofossils, magnetite crystals, and organic molecules were each given an abiotic explanation over subsequent years, and the consensus shifted away from a biological interpretation. Nothing about the original data was fraudulent; the reasoning simply had alternatives that were not excluded. This is the standard the course applies to every biosignature claim."],
   ["biomorph","false positive","contextual evidence","abiotic mimic"]),
  ("Controls, contamination, and confidence", [
    "Terrestrial contamination is the dominant risk in any sample-handling chain. Countermeasures include documented cleanliness levels, blanks carried through the full procedure, witness plates, sterilised sampling hardware, and reference libraries of every organism and reagent that touched the sample.",
    "Confidence should be reported on a scale, not asserted as a binary. Community frameworks such as the confidence-of-life-detection scale run from anomaly detected, through contamination excluded and abiotic explanations addressed, to independent confirmation with a second method or instrument. Reporting a level, with the specific evidence that supports it, is more scientifically useful and more honest than a yes-or-no claim."],
   ["procedural blank","witness plate","confidence scale","independent replication"]),
  ("Designing a detection sequence", [
    "A staged design tests the cheapest and most discriminating hypotheses first. Context comes first: is the environment plausibly habitable, and is the sample from a setting that would preserve a signature? Then broad survey measurements, then specific assays, then confirmatory analysis by an independent method.",
    "Instruments should be selected for what they can exclude, not only for what they can detect. Mass spectrometry, Raman spectroscopy, microscopy, chromatography, and chirality assays each have blind spots, and combining methods with different failure modes is what makes a claim robust. This is the same logic used in Term 2 when locating a failure in the oxygen cascade."],
   ["staged design","orthogonal methods","preservation potential","detection limit"]),
 ],
 figure=dict(kind="flow", title="Life-detection decision chain",
   caption="A claim advances only by surviving each stage. Most historical claims failed at the third box, not the first.",
   items=["Anomalous signal","Instrument and contamination checks","Abiotic explanations tested","Contextual evidence assembled","Independent method confirms","Confidence level reported"]),
 practice=[
  dict(q="Oxygen alone is a weak exoplanet biosignature because it",
    opts=["cannot be detected spectroscopically","can accumulate abiotically through photolysis of water and hydrogen escape","is never produced by biology","is chemically inert"],
    a=1, why="Photochemical routes on water-rich planets, particularly around active M dwarfs, can produce substantial oxygen with no biology, which is why disequilibrium pairs are preferred."),
  dict(q="The strongest argument for oxygen and methane together as a biosignature is that",
    opts=["both are rare in the universe","they react with each other, so their coexistence implies continuous replenishment","methane is only made by animals","oxygen destroys all abiotic chemistry"],
    a=1, why="Coexistence of a reduced and an oxidised species at detectable levels requires a large ongoing source, which is difficult to sustain abiotically."),
  dict(q="Enantiomeric excess in a returned sample would be a meaningful biosignature because abiotic chemistry generally produces",
    opts=["only L-amino acids","racemic or near-racemic mixtures","only D-amino acids","no amino acids at all"],
    a=1, why="Without a chiral-selecting process, both forms are produced roughly equally, and any excess racemises over geological time unless maintained."),
  dict(q="The main lesson of the ALH 84001 debate for life-detection practice is that",
    opts=["meteorites should not be studied","multiple independent lines of evidence must each survive scrutiny for abiotic alternatives","morphology is always conclusive","isotope data cannot be trusted"],
    a=1, why="Each individual line had an abiotic explanation. Robustness comes from lines that fail in different ways, not from the number of lines."),
  dict(q="A procedural blank differs from an instrument blank because it is",
    opts=["measured on a different instrument entirely","carried through every step of the sampling and preparation chain","collected after the sample is analysed","a theoretical calculation"],
    a=1, why="Only a full-chain blank captures contamination introduced by handling, containers, and reagents rather than by the detector alone."),
  dict(q="In a staged detection design, contextual habitability assessment comes first because it",
    opts=["is the most expensive step","determines whether a positive result is even interpretable and where to sample","replaces the need for controls","guarantees a positive detection"],
    a=1, why="Context governs both sampling strategy and the prior weight given to any anomaly, and it is comparatively cheap to establish."),
  dict(q="Two instruments with correlated failure modes provide weaker confirmation than two with independent failure modes because",
    opts=["correlated instruments are less sensitive","a shared artefact would produce agreement without indicating a real signal","independent instruments are always more accurate","correlation reduces detection limits"],
    a=1, why="Agreement is only evidence if the methods could have disagreed for independent reasons; shared systematics defeat that."),
  dict(q="Reporting a detection on a confidence scale rather than as a binary claim is preferred because it",
    opts=["avoids all criticism","communicates which specific evidential requirements have been met and which remain open","increases the chance of publication","removes the need for peer review"],
    a=1, why="A scale makes the state of the evidence legible and allows the claim to be revised as further requirements are met or fail."),
  dict(q="Which sample setting would generally have the highest preservation potential for organic biosignatures on Mars?",
    opts=["Freshly exposed surface regolith in an equatorial plain","Fine-grained sediments or evaporites shielded from radiation, such as subsurface or recently exposed strata","Volcanic glass at the surface","Dust suspended in the atmosphere"],
    a=1, why="Ionising radiation degrades surface organics over millions of years; fine-grained, shielded deposits retain them far better."),
  dict(q="A technosignature search differs from a biosignature search principally in that it",
    opts=["requires no assumptions at all","assumes a particular technological developmental path, gaining specificity but narrowing scope","can only be done from space","is guaranteed to be free of false positives"],
    a=1, why="Technosignatures are highly specific if found, but the search space is defined by assumptions about technology, and terrestrial radio interference is a persistent false-positive source."),
 ],
 applied=[
  ("Astrobiology Case Study: take a published or instructor-supplied biosignature claim and evaluate it. State the observation, the biological interpretation, at least two abiotic alternatives, the contamination controls reported, and the confidence level you would assign with justification.",
   "The grade rests on the abiotic alternatives and the controls section, not on the verdict reached."),
  ("Design a four-stage life-detection sequence for a specific target environment. For each stage give the measurement, the instrument, the decision rule for proceeding, and the false-positive mode it is intended to exclude.",
   "Decision rules must be stated before results, which is the point of a staged design."),
 ],
)

CONTENT["ch14"] = dict(
 bridge=("Space biology inverts the question again. Instead of asking where life could exist, it asks what happens to "
         "known organisms, including the crew, when the environment changes in ways no lineage on Earth has ever "
         "experienced."),
 sections=[
  ("Model organisms and what they have shown", [
    "Space biology relies on a small set of organisms: bacteria, yeast, Arabidopsis, Caenorhabditis elegans, Drosophila, and rodents, chosen for short life cycles, sequenced genomes, and modest resource demands. Results consistently show altered gene expression, changes in biofilm formation and antibiotic response in bacteria, altered root architecture and cell wall composition in plants, and muscle and bone changes in rodents that parallel human findings.",
    "Two organisms have become emblematic of survival limits: tardigrades, which survive vacuum and radiation in an anhydrobiotic state, and Deinococcus radiodurans, which repairs shattered chromosomes. Neither is evidence that complex life travels between planets easily, but both extend the envelope of what a dormant organism can endure, which matters for panspermia arguments and for planetary protection."],
   ["model organism","anhydrobiosis","biofilm","gene expression"]),
  ("Altered gravity", [
    "Gravity affects biology directly through mechanotransduction and indirectly by removing buoyancy-driven convection and sedimentation. Cells sense mechanical load through cytoskeleton, adhesion complexes, and stretch-activated channels, and removing load alters signalling, differentiation, and cell shape.",
    "Indirect effects are often larger than direct ones. Without convection, unstirred boundary layers alter nutrient and gas transport around cells, roots, and leaves. Distinguishing a true gravity-sensing effect from a transport artefact requires onboard centrifuge controls, which is why 1 g controls in flight are the methodological gold standard rather than ground controls alone."],
   ["mechanotransduction","unstirred layer","onboard 1 g control","simulated microgravity"]),
  ("The radiation environment", [
    "Beyond the magnetosphere, organisms face galactic cosmic rays, dominated by high-energy protons and high-charge, high-energy nuclei, plus episodic solar particle events. Cosmic-ray nuclei deposit energy in dense tracks, producing clustered DNA damage that is harder to repair than the sparse damage typical of terrestrial radiation.",
    "Consequences include cancer risk, degenerative tissue effects, and possible central nervous system effects, with substantial uncertainty in the risk models because there is no matching human exposure dataset. Shielding is limited by mass and by secondary particle production in the shield itself, so mission architecture, transit duration, and storm shelters carry much of the mitigation."],
   ["galactic cosmic ray","HZE particle","clustered damage","secondary particles"]),
  ("Closed ecosystems and the crew", [
    "A bioregenerative life-support system aims to close the loops for oxygen, water, carbon, and waste using plants, algae, and microbial processing. Biosphere 2 remains the most instructive attempt, where unexpected oxygen decline traced to soil microbial respiration and carbon uptake by concrete demonstrated how a single unmodelled sink can destabilise a closed system.",
    "For humans, the recognised hazard framework covers radiation, isolation and confinement, distance from Earth, gravity fields, and hostile closed environments. Countermeasures are exercise, nutrition, pharmacology, scheduling and lighting for circadian entrainment, psychological support, shielding, and habitat design. Each is partial, and residual risk is documented rather than eliminated, which is the professional standard the capstone should adopt."],
   ["bioregenerative","loop closure","five hazards","residual risk"]),
 ],
 figure=dict(kind="flow", title="Closing the loop in a habitat",
   caption="Every arrow needs a rate, a buffer, and a failure mode. Biosphere 2's oxygen decline came from a sink absent from the model, not from a broken arrow.",
   items=["Crew metabolism (O2 out, CO2 in)","CO2 to crop chamber","Photosynthesis: O2 and biomass","Harvest and waste processing","Water recovery and nutrients back to crops"]),
 practice=[
  dict(q="An onboard 1 g centrifuge control is methodologically important because it separates",
    opts=["radiation effects from temperature effects","true gravity-dependent responses from other spaceflight factors such as launch stress and radiation","genetic from epigenetic effects","day from night cycles"],
    a=1, why="Flight samples share launch, radiation, vibration, and cabin conditions; only an in-flight 1 g arm isolates gravity as the variable."),
  dict(q="Galactic cosmic rays are more biologically damaging per unit dose than terrestrial gamma radiation mainly because they",
    opts=["deliver larger total doses","deposit energy in dense tracks, producing clustered DNA damage that repair systems handle poorly","are absorbed entirely by the skin","occur only during solar storms"],
    a=1, why="High linear energy transfer produces complex, clustered lesions. Repair fidelity falls, so relative biological effectiveness is higher."),
  dict(q="Adding shielding mass does not straightforwardly solve the cosmic-ray problem because",
    opts=["cosmic rays pass through all matter unaffected","high-energy nuclei produce secondary particle showers within the shield","shielding increases radiation output","no material blocks protons"],
    a=1, why="Fragmentation in the shield produces secondaries; poorly chosen materials and thicknesses can increase dose to the crew."),
  dict(q="In microgravity, an apparent metabolic change in a bacterial culture may actually reflect",
    opts=["altered gene regulation only","changed transport conditions from absent convection producing unstirred boundary layers","increased gravity sensing","higher temperature only"],
    a=1, why="Diffusion-limited microenvironments alter nutrient and waste concentrations at the cell surface, mimicking a physiological change."),
  dict(q="The oxygen decline in Biosphere 2 was ultimately attributed to",
    opts=["a leak in the structure","soil microbial respiration combined with carbon dioxide uptake by concrete","insufficient plant biomass at the start","failure of the water recycling system"],
    a=1, why="Organic-rich soils respired heavily, and the resulting carbon dioxide was absorbed by curing concrete, breaking the expected carbon balance."),
  dict(q="Tardigrade survival of vacuum exposure is possible mainly because they",
    opts=["maintain normal metabolism in vacuum","enter an anhydrobiotic state with near-total metabolic suspension and protective molecules","have a thick mineralised shell","photosynthesise"],
    a=1, why="Desiccation-tolerant dormancy with protective proteins and sugars, plus efficient repair on rehydration, underlies the tolerance."),
  dict(q="The NASA five-hazard framework for human spaceflight includes radiation, isolation and confinement, distance from Earth, gravity fields, and",
    opts=["hostile and closed environments","micrometeoroids","launch acceleration","fuel toxicity"],
    a=0, why="The fifth hazard is the closed environment itself, covering air and water quality, microbial ecology, noise, lighting, and habitability."),
  dict(q="Which countermeasure most directly addresses bone loss rather than its downstream consequences?",
    opts=["Increased dietary calcium alone","High-load resistive exercise reproducing peak skeletal strain","Extended sleep scheduling","Radiation shielding"],
    a=1, why="Bone responds to strain magnitude; nutrition supports the process but does not supply the mechanical signal."),
  dict(q="A student proposes that panspermia is proven by tardigrade vacuum survival. The strongest objection is that",
    opts=["tardigrades do not exist in space","surviving brief exposure in dormancy does not establish transfer, transit over geological time, or successful arrival and colonisation","tardigrades are too small","vacuum is not present in space"],
    a=1, why="Survival is one necessary condition among several. Ejection, transit shielding, atmospheric entry, and establishment each remain unaddressed."),
  dict(q="Elevated antibiotic resistance and biofilm formation observed in spaceflight bacterial cultures matter operationally because they",
    opts=["prove bacteria evolve faster in space","affect crew infection risk and hardware biofouling, both of which must be managed in a closed habitat","have no practical consequence","only apply to plant pathogens"],
    a=1, why="The operational implications are medical and engineering; the underlying mechanism is still under study and may be transport-related."),
 ],
 applied=[
  ("Design a space-biology experiment with a stated hypothesis, an onboard 1 g control, defined endpoints, sample sizes, and a statement of what a null result would mean. Identify the resource constraint most likely to force a compromise.",
   "Crew time and upmass are the usual binding constraints; the null-result statement is the integrity check."),
  ("Capstone draft workshop: submit the investigation question, target environment, evidence base, and analysis plan for your capstone, plus a written peer review of one classmate's draft using the course rubric.",
   "Peer review is graded on the quality of the critique, not on agreement with the author."),
 ],
)

CONTENT["ch15"] = dict(
 bridge=("The course ends where its obligations begin. Planetary protection is the point at which astrobiology's "
         "scientific standards, evidence, controls, and honest uncertainty, become binding operational and ethical "
         "requirements."),
 sections=[
  ("Forward and backward contamination", [
    "Forward contamination is the transfer of terrestrial organisms to another body, which would compromise any future life detection and could in principle disturb an indigenous biosphere. Backward contamination is the return of extraterrestrial material to Earth, where the hazard is considered very low but the consequences of error are severe.",
    "COSPAR planetary protection policy assigns categories according to target body and mission type, from Category I for bodies of no biological interest through Category IV subcategories for landed missions to Mars, to Category V for sample return, distinguished as unrestricted or restricted according to whether the source body could harbour life. Requirements scale accordingly: documentation, bioburden limits, sterilisation, trajectory biasing, and containment."],
   ["forward contamination","COSPAR categories","bioburden","restricted Earth return"]),
  ("Implementation and its limits", [
    "Implementation includes dry heat microbial reduction, vapour-phase sterilisation, cleanroom assembly, bioburden assay, special regions analysis, and, for sample return, break-the-chain architectures and receiving facilities at high biosafety containment.",
    "Sterilisation is never absolute; it is a probability statement. Requirements are written as a probability of contaminating a special region, and compliance is demonstrated by counting and modelling rather than by proving zero. That framing, an explicit risk budget rather than an absolute guarantee, is worth taking seriously as a model for how scientific uncertainty enters policy generally."],
   ["microbial reduction","special region","break the chain","risk budget"]),
  ("Ethics beyond contamination", [
    "Ethical debate extends past sample safety. Positions range from instrumental, protecting scientific value, to intrinsic, holding that even microbial life or pristine environments have standing independent of human use. Questions about resource extraction, commercial activity, terraforming, and permanent settlement each involve trade-offs between exploration, preservation, and human interests.",
    "There are also nearer questions: informed consent and risk exposure for crew, equity in who participates in and benefits from space activity, and the responsibilities of researchers communicating uncertain findings to the public. Astrobiology has repeatedly been the subject of overstated headlines, and disciplined communication is part of professional practice, not an optional extra."],
   ["intrinsic value","planetary stewardship","terraforming","science communication"]),
  ("Integration: defending an evidence-based claim", [
    "The capstone requires a defensible position under uncertainty: a clear question, a stated framework, evidence assembled with its quality made explicit, alternatives considered, a conclusion proportionate to the evidence, and identified limitations. A defence is judged on the handling of the weakest part of the argument, not the strongest.",
    "This connects back to Week 1. The operational definition of life drafted then determines what counts as evidence now, and every intervening week supplied constraints: what cells require, what physiology needs, what environments provide, and what instruments can and cannot exclude. That chain, from definition to measurement to claim, is the course's actual argument."],
   ["proportionality","limitation statement","defensible claim","uncertainty communication"]),
 ],
 figure=dict(kind="compare", title="Two directions of contamination risk",
   caption="The two problems have different probabilities and different consequences, which is why the policy response to each is asymmetric.",
   left=("Forward", ["Earth organisms carried outward","Compromises future life detection","Managed by bioburden limits and sterilisation","Applies to all landed missions"]),
   right=("Backward", ["Returned material brought to Earth","Considered low probability, high consequence","Managed by containment and break-the-chain design","Applies to restricted Category V missions"])),
 practice=[
  dict(q="A mission returning samples from a body that could harbour life is classified under COSPAR policy as",
    opts=["Category II","Category III","Category IV","Category V, restricted Earth return"],
    a=3, why="Restricted Category V applies when the source body cannot be shown to be free of a potential biological hazard, triggering containment and receiving-facility requirements."),
  dict(q="Planetary protection requirements are written as probabilities rather than absolute guarantees because",
    opts=["agencies are not committed to the policy","sterilisation is a statistical process and zero contamination cannot be demonstrated","the policy is voluntary","spacecraft are assembled without controls"],
    a=1, why="Microbial reduction follows kill kinetics; compliance is demonstrated by bioburden assay and modelled probability against a stated limit."),
  dict(q="The strongest scientific argument for strict forward-contamination controls is that terrestrial organisms could",
    opts=["reproduce instantly on any planet","confound future life-detection results, making any positive detection uninterpretable","damage the spacecraft structure","alter planetary orbits"],
    a=1, why="Irreversibility is the key point: once introduced, contamination cannot be removed, and the scientific value of the site is permanently degraded."),
  dict(q="A 'special region' on Mars is defined as an area where",
    opts=["a previous mission landed","terrestrial organisms could plausibly propagate, or where Martian life might exist","the surface is smooth enough for landing","radiation is lowest"],
    a=1, why="The definition is based on temperature and water activity thresholds that would permit terrestrial microbial replication."),
  dict(q="Break-the-chain architecture in a sample return mission ensures that",
    opts=["the sample is destroyed if contaminated","no surface that contacted the sampled body's environment is exposed on the returning vehicle path to Earth","the mission never returns","samples are analysed only in orbit"],
    a=1, why="Physical isolation of contacted surfaces prevents uncontained material from reaching Earth's environment outside the containment system."),
  dict(q="An argument that microbial extraterrestrial life has intrinsic value implies that",
    opts=["it should be preserved only if useful to human science","its preservation has weight independent of human benefit","only complex life deserves protection","planetary protection is unnecessary"],
    a=1, why="Intrinsic value claims ground obligations in the entity itself, in contrast to instrumental arguments that appeal to scientific or economic utility."),
  dict(q="A research team finds an ambiguous organic signal in a Martian sample. The most professionally responsible communication is to",
    opts=["announce the discovery of life to secure funding","report the observation, the abiotic alternatives, the controls, and an explicit confidence level","withhold the result until absolutely certain","publish only the negative interpretation"],
    a=1, why="Full reporting with calibrated confidence serves both the science and the public record; silence and overstatement both fail."),
  dict(q="In defending a capstone under uncertainty, the strongest posture is to",
    opts=["assert the conclusion with maximum confidence","state the conclusion proportionately and identify the weakest link in the evidence chain yourself","avoid stating a conclusion","cite as many sources as possible"],
    a=1, why="Proportionality and self-identified limitations demonstrate command of the evidence and are what the oral-defence rubric rewards."),
  dict(q="Terraforming debates involve a trade-off principally between",
    opts=["cost and speed only","human expansion and the preservation of a possibly inhabited or scientifically pristine environment","radiation and gravity","robotic and crewed missions"],
    a=1, why="The core tension is between irreversible transformation for human use and the scientific and ethical claims of the existing environment."),
  dict(q="The through-line connecting Week 1 to Week 15 is that",
    opts=["biology is more important than physics","the operational definition of life adopted at the start determines what counts as evidence at the end","planetary protection replaces the need for biology","astrobiology is unrelated to human physiology"],
    a=1, why="Definition determines measurement, measurement determines claims, and claims carry ethical and operational obligations. That chain is the course's argument."),
 ],
 applied=[
  ("Final capstone: submit a 6-8 page investigation or habitability assessment with a habitability matrix, a diagram, a presentation, and an individual reflection. The reflection must state what would change your conclusion.",
   "The reflection is assessed for genuine falsifiability, not for expressions of humility."),
  ("Write a 400-word planetary protection brief for a proposed landed mission to a target of your choice. Assign the COSPAR category, justify it, list three implementation requirements, and identify the requirement most likely to be contested during review.",
   "Category justification must reference the target's potential for supporting terrestrial replication or indigenous life."),
 ],
)
