# -*- coding: utf-8 -*-
CONTENT = {}

CONTENT["ch06"] = dict(
 bridge=("Human physiology is the reference system for every crewed mission risk assessment. Before you can say what "
         "spaceflight does to a body, you need the vocabulary and the regulatory logic that describe the body at rest "
         "on Earth."),
 sections=[
  ("Anatomical language", [
    "Anatomical position, the erect body facing forward with palms anterior, anchors all directional terms: superior and inferior, anterior and posterior, medial and lateral, proximal and distal, superficial and deep. Planes divide the body sagittally, frontally, and transversely. Cavities, dorsal and ventral, house and protect organs.",
    "The vocabulary exists because ordinary spatial language is ambiguous once a body can move. In spaceflight the ambiguity returns in a new form, since 'up' has no meaning in free fall, and habitat design has to supply visual verticals deliberately to prevent disorientation."],
   ["anatomical position","sagittal plane","serous membrane","body cavity"]),
  ("Tissues", [
    "Four primary tissue types build every organ. Epithelium covers surfaces and lines cavities, is avascular, and regenerates rapidly. Connective tissue, the most varied class, supports and binds through cells scattered in an extracellular matrix, from loose areolar tissue to bone and blood. Muscle tissue contracts: skeletal, cardiac, and smooth. Nervous tissue conducts and integrates signals.",
    "Organs are combinations. The stomach has an epithelial lining, connective submucosa, smooth muscle layers, and enteric nervous tissue. Recognising the four types in a section is the core practical skill of a histology laboratory and the basis of interpreting damage, since each tissue type fails and repairs differently."],
   ["epithelium","extracellular matrix","histology","regeneration"]),
  ("Homeostasis as control theory", [
    "A homeostatic loop needs a sensed variable, a receptor, an integrating centre with a set point, and an effector. Negative feedback stabilises; positive feedback drives a process to completion. Set points are not fixed constants: they are adjusted by circadian rhythm, acclimatisation, and disease, which is why a single reference value is a poor description of a healthy body.",
    "Failure modes are informative. Loop gain that is too low leaves the variable drifting; gain that is too high produces oscillation; delay in the feedback path produces overshoot. Human thermoregulation, fluid balance, and blood pressure control all show these behaviours, and all three are disturbed within days of arriving in microgravity."],
   ["set point","loop gain","acclimatisation","overshoot"]),
  ("The integument and thermoregulation", [
    "Skin is the largest organ: epidermis with keratinised stratified squamous epithelium, dermis with vessels, nerves, and glands, and hypodermis storing fat. It provides a mechanical and microbial barrier, restricts water loss, synthesises vitamin D, and senses touch, pressure, temperature, and pain.",
    "Thermoregulation uses all four heat transfer routes: conduction, convection, radiation, and evaporation. Vasodilation and sweating dump heat; vasoconstriction, shivering, and behaviour conserve it. In a spacecraft, convection is weak without gravity-driven air movement, evaporation depends on cabin humidity control, and radiative exchange dominates for the vehicle, so thermal comfort must be engineered rather than assumed."],
   ["evaporative cooling","vasodilation","core temperature","insensible loss"]),
 ],
 figure=dict(kind="flow", title="The negative feedback loop",
   caption="Every homeostatic mechanism in the course maps onto this sequence. Where a system fails, one element in the chain is missing, delayed, or mistuned.",
   items=["Stimulus (variable deviates)","Receptor detects","Control centre compares to set point","Effector responds","Variable returns toward set point"]),
 practice=[
  dict(q="The wrist is ___ to the elbow and ___ to the fingers.",
    opts=["proximal; distal","distal; proximal","medial; lateral","superficial; deep"],
    a=1, why="Distal means farther from the point of attachment to the trunk; the wrist is farther from the trunk than the elbow but closer than the fingers."),
  dict(q="A tissue is avascular, sits on a basement membrane, and regenerates rapidly after abrasion. It is",
    opts=["connective tissue","epithelium","smooth muscle","nervous tissue"],
    a=1, why="Avascularity plus a basement membrane and high turnover are epithelial hallmarks; nutrients diffuse from the underlying connective tissue."),
  dict(q="Blood is classified as connective tissue because it",
    opts=["contracts under stimulation","consists of cells dispersed in an extensive extracellular matrix","lines a body cavity","conducts electrical signals"],
    a=1, why="Plasma is the matrix. The classification is by structural organisation, not by function or physical state."),
  dict(q="Blood clotting is a positive feedback process because each step",
    opts=["opposes the initiating stimulus","accelerates the process until the stimulus is removed by clot formation","resets the set point","requires conscious control"],
    a=1, why="Activated platelets recruit more platelets, amplifying until the vessel is sealed. Positive feedback suits processes that must reach completion quickly."),
  dict(q="A control system that oscillates widely around its set point most likely suffers from",
    opts=["excessive gain or delay in the feedback path","absence of a receptor","absence of an effector","an incorrectly high set point"],
    a=1, why="High gain with lag produces overshoot and hunting. A missing receptor or effector would give drift, not oscillation."),
  dict(q="In a spacecraft cabin, evaporative cooling becomes less effective mainly when",
    opts=["cabin humidity rises because water vapour is not carried away by convection","core temperature falls","skin blood flow increases","radiation from the vehicle increases"],
    a=1, why="Evaporation depends on the vapour pressure gradient. Weak convection leaves a saturated boundary layer at the skin, so humidity control and forced airflow become essential."),
  dict(q="Vitamin D synthesis in skin requires",
    opts=["ultraviolet B exposure acting on a cholesterol precursor","dietary calcium only","infrared radiation","high ambient humidity"],
    a=0, why="UVB converts 7-dehydrocholesterol to previtamin D3. Shielded habitats block UVB, so dietary or supplemental intake is required in spaceflight."),
  dict(q="Which sequence correctly orders the levels of structural organisation?",
    opts=["cell, tissue, organ, organ system, organism","tissue, cell, organ, organism, organ system","organ, tissue, cell, organ system, organism","cell, organ, tissue, organ system, organism"],
    a=0, why="Cells combine into tissues, tissues into organs, organs into systems, and systems into the organism."),
  dict(q="A patient's core temperature is 37.8 degrees Celsius during infection. The most accurate physiological description is that",
    opts=["homeostasis has failed entirely","the set point has been raised and the body is regulating to the new value","the receptors have stopped functioning","effectors are producing random output"],
    a=1, why="Fever is regulated hyperthermia: pyrogens raise the hypothalamic set point, and shivering and vasoconstriction actively defend the higher value."),
  dict(q="The strongest reason anatomical terminology is standardised rather than descriptive is that",
    opts=["it sounds more professional","terms remain unambiguous regardless of body position or orientation","it is required by law","it shortens medical records"],
    a=1, why="Terms are defined relative to anatomical position, so 'anterior' means the same thing whether the person is standing, lying down, or in free fall."),
 ],
 applied=[
  ("Identify the four primary tissue types in three unlabelled histology images and justify each identification using two structural features. Then predict how each tissue would respond to a deep abrasion.",
   "Justification by feature, not by appearance-matching, is the point of the exercise."),
  ("Map the thermoregulatory loop for a crew member exercising in a habitat with failed cabin air circulation. Identify which of the four heat-transfer routes is compromised and what the physiological consequence is over 30 minutes.",
   "Expect convection and evaporation to be named, with rising core temperature and cardiovascular strain as the consequence."),
 ],
)

CONTENT["ch07"] = dict(
 bridge=("Bone and muscle are load-adapted tissues: they build to the forces they experience and dismantle when those "
         "forces disappear. That single principle explains why skeletal loss is one of the defining medical problems of "
         "long-duration spaceflight."),
 sections=[
  ("Bone as an adaptive material", [
    "Bone is a composite: collagen provides tensile toughness, hydroxyapatite provides compressive stiffness. Compact bone resists bending in shafts; spongy bone distributes load at the ends along trabecular lines that follow principal stress directions. Osteoblasts deposit matrix, osteoclasts resorb it, and osteocytes sense strain.",
    "Remodelling responds to mechanical loading, a relationship known as Wolff's law. Remove load and resorption outpaces deposition. Astronauts lose roughly 1 to 1.5 per cent of bone mineral density per month in weight-bearing sites without countermeasures, a rate an order of magnitude faster than typical postmenopausal loss on Earth."],
   ["hydroxyapatite","trabecula","Wolff's law","bone mineral density"]),
  ("Joints and muscle mechanics", [
    "Synovial joints permit specified motions: hinge, ball-and-socket, pivot, saddle, condyloid, and plane. Skeletal muscle contracts by cross-bridge cycling under the sliding filament model, with force graded by motor unit recruitment and firing rate.",
    "Muscle force depends on cross-sectional area, length relative to optimum, and shortening velocity. Because muscle attaches close to joints, muscles usually trade force for speed and range: a large muscle force produces a smaller load force but moves it faster and farther."],
   ["sarcomere","motor unit","cross-bridge cycle","antagonist pair"]),
  ("Levers and torque", [
    "A lever is a rigid bar rotating about a fulcrum. Torque equals force times perpendicular distance to the axis. In first-class levers the fulcrum lies between effort and load, as at the atlanto-occipital joint; in second-class levers the load is between, as in plantar flexion rising onto the toes; in third-class levers the effort is between, which describes most skeletal muscles including the biceps at the elbow.",
    "Third-class levers have mechanical advantage less than one, meaning muscle force exceeds load force. A 5 kilogram mass held 30 centimetres from the elbow with a biceps insertion 4 centimetres from the joint requires roughly 7.5 times the load force, about 370 newtons. That number explains both why muscles are strong relative to the loads they lift and why joint reaction forces are high."],
   ["torque","mechanical advantage","fulcrum","moment arm"]),
  ("Work, power, and loading", [
    "Work is force times displacement in the direction of the force; power is work per unit time. In movement analysis, positive work accompanies concentric contraction and negative work accompanies eccentric contraction, where muscle lengthens under load and absorbs energy. Eccentric loading generates the highest tissue stresses and the most delayed-onset soreness.",
    "Countermeasures in orbit exploit this directly. Resistive exercise devices reproduce high peak loads rather than long duration, because loading magnitude, not total activity, drives bone and muscle maintenance. Treadmill exercise with harness loading and cycle ergometry address cardiovascular and coordination outcomes, but the resistive component carries the skeletal case."],
   ["concentric","eccentric","power output","loading rate"]),
 ],
 figure=dict(kind="compare", title="Lever classes in the body",
   caption="Most human joints are third-class levers, trading force for range and speed. This is why muscle forces and joint reaction forces greatly exceed the external load.",
   left=("Second-class (load in middle)", ["Rising onto the toes","Mechanical advantage greater than 1","Effort force smaller than load","Rare in the human body"]),
   right=("Third-class (effort in middle)", ["Biceps flexing the elbow","Mechanical advantage less than 1","Effort force larger than load","Fast, wide range of movement"])),
 practice=[
  dict(q="A 5 kg mass is held in the hand 30 cm from the elbow joint; the biceps inserts 4 cm from the joint. The approximate muscle force required is",
    opts=["about 49 N","about 370 N","about 6.5 N","about 1500 N"],
    a=1, why="Torque balance gives F x 0.04 = 49 x 0.30, so F is about 368 N. The seven-and-a-half-fold multiplication is characteristic of third-class levers."),
  dict(q="Bone loss in microgravity occurs principally because",
    opts=["calcium cannot be absorbed in space","mechanical strain signals fall, so resorption exceeds deposition","cosmic radiation destroys hydroxyapatite","osteoblasts cannot divide without gravity"],
    a=1, why="Osteocytes sense strain; removing load removes the signal that maintains deposition. Radiation and absorption issues exist but are secondary to unloading."),
  dict(q="Trabecular bone is oriented along lines of principal stress. This is direct evidence for",
    opts=["genetic determination of bone shape independent of use","adaptive remodelling in response to mechanical loading","the tensile role of hydroxyapatite","the absence of osteoclast activity in spongy bone"],
    a=1, why="This is Wolff's law: architecture follows loading history, which is why disuse changes trabecular pattern, not just density."),
  dict(q="Eccentric contraction is defined as the muscle",
    opts=["shortening while generating force","lengthening while generating force","generating force with no length change","relaxing completely under load"],
    a=1, why="Lengthening under tension absorbs energy, generates the highest forces per unit of muscle activation, and causes the most microdamage."),
  dict(q="A resistive exercise device is preferred over long-duration low-load cycling for skeletal maintenance because bone responds primarily to",
    opts=["total exercise duration","peak strain magnitude and rate","heart rate elevation","caloric expenditure"],
    a=1, why="Short bouts of high-magnitude, high-rate loading are osteogenic; low-magnitude repetition is not, regardless of duration."),
  dict(q="Increasing the moment arm of a muscle by 25 per cent, holding load constant, changes the required muscle force by approximately",
    opts=["increasing it 25 per cent","decreasing it 20 per cent","no change","decreasing it 50 per cent"],
    a=1, why="Force is inversely proportional to moment arm, so multiplying the arm by 1.25 multiplies the force by 0.8."),
  dict(q="Graded muscle force in a whole muscle is achieved mainly through",
    opts=["varying the force of each individual cross-bridge","recruiting more motor units and increasing firing rate","changing the number of muscle fibres present","altering bone density"],
    a=1, why="Individual cross-bridges generate near-constant force; grading is a population and frequency effect."),
  dict(q="A crew member lifts a 20 kg mass 1.2 m in 0.8 s. Mean mechanical power output is approximately",
    opts=["24 W","294 W","196 W","2.4 W"],
    a=1, why="Work equals mgh, about 235 J; divided by 0.8 s gives roughly 294 W."),
  dict(q="Joint reaction force is typically much larger than the external load because",
    opts=["gravity acts twice on the limb","muscle forces acting through short moment arms add to the load at the joint","joints amplify external forces directly","cartilage generates additional force"],
    a=1, why="The large muscle force needed for torque balance is transmitted through the joint surface along with the external load."),
  dict(q="On a surface with 0.38 g, the muscle force required to hold a given mass statically at the same posture would be",
    opts=["unchanged, because mass is unchanged","about 38 per cent of the Earth value, because weight scales with local gravity","larger, because muscles weaken","zero, because the object is weightless"],
    a=1, why="Static torque balance depends on weight, not mass. This is why partial-gravity surface operations are expected to under-load the skeleton relative to Earth."),
 ],
 applied=[
  ("Biophysics Set A: analyse three joint actions as levers. For each, identify the class, measure or estimate the moment arms, compute the muscle force for a stated load, and state one assumption your model makes that a real joint violates.",
   "Common violations: muscle line of action is not perpendicular, multiple muscles share the load, joint axis migrates."),
  ("Design a 45-minute in-flight exercise protocol justified by loading physiology rather than by terrestrial fitness convention. State the target tissue for each block and the variable that must be preserved.",
   "The justification should reference peak strain magnitude for bone and high-force eccentric work for muscle."),
 ],
)

CONTENT["ch08"] = dict(
 bridge=("Neural signalling is bioelectricity: a battery built by ion pumps and discharged through gated channels. "
         "Sensory systems are its front end, and both are measurably altered when the vestibular system loses the "
         "gravitational reference it evolved with."),
 sections=[
  ("Membrane potentials and the action potential", [
    "The resting membrane potential, near -70 millivolts in neurons, arises from unequal ion distributions maintained by the sodium-potassium pump and from selective permeability, dominated at rest by potassium leak channels. The Nernst equation gives the equilibrium potential for a single ion; the Goldman equation weights several by permeability.",
    "An action potential is a regenerative event: depolarisation to threshold opens voltage-gated sodium channels, sodium entry drives further depolarisation, inactivation and delayed potassium efflux repolarise the membrane. It is all-or-none, so intensity is coded by frequency, not amplitude. Myelination and larger axon diameter increase conduction velocity, the former by saltatory conduction between nodes of Ranvier."],
   ["resting potential","threshold","saltatory conduction","refractory period"]),
  ("Synapses and integration", [
    "At a chemical synapse, calcium entry triggers vesicle fusion and neurotransmitter release; receptors on the postsynaptic membrane produce excitatory or inhibitory potentials. These are graded and sum temporally and spatially at the axon hillock, which decides whether threshold is reached.",
    "Integration is the computational step. A neuron is not a relay but a comparator over hundreds or thousands of inputs, and this is where drugs, toxins, and neuromodulators exert their effects. Reaction-time experiments measure the sum of transduction, conduction, synaptic delay, integration, and motor execution, which is why interpreting them requires knowing which stage dominates."],
   ["neurotransmitter","summation","synaptic delay","neuromodulation"]),
  ("Sensory physics: optics and acoustics", [
    "The eye is a refracting system: the cornea provides most of the refractive power, the lens accommodates, and the retina transduces light through rods and cones. Refractive errors are geometric, correctable by lenses whose power in dioptres is the reciprocal of focal length in metres.",
    "Hearing is mechanical: the tympanic membrane and ossicles impedance-match air to cochlear fluid, and the basilar membrane performs a frequency decomposition, with high frequencies near the base and low near the apex. Sound intensity is described logarithmically in decibels, so a 10 dB rise is a tenfold intensity increase. The vestibular apparatus, semicircular canals for angular acceleration and otolith organs for linear acceleration and gravity, is the third mechanical sense and the one most disrupted in free fall."],
   ["accommodation","dioptre","tonotopic map","otolith"]),
  ("Endocrine regulation and stress", [
    "Hormones act slowly and persistently compared with neural signals. The hypothalamus and pituitary sit at the top of several axes, controlling thyroid activity, adrenal cortisol, growth, and reproduction through negative feedback. Water balance runs through antidiuretic hormone; calcium through parathyroid hormone and calcitonin.",
    "The stress response combines a fast sympathetic-adrenal-medullary catecholamine surge with a slower hypothalamic-pituitary-adrenal cortisol response. Sustained elevation impairs immune function, sleep, and bone maintenance, and all three are documented concerns in long-duration missions, where isolation, workload, and altered light-dark cycles act together."],
   ["HPA axis","negative feedback","cortisol","circadian entrainment"]),
 ],
 figure=dict(kind="flow", title="From stimulus to response",
   caption="A reaction-time measurement contains every stage in this chain. Attributing a change to one stage requires an experimental design that isolates it.",
   items=["Stimulus","Receptor transduction","Afferent conduction","CNS integration","Efferent conduction","Effector response"]),
 practice=[
  dict(q="A neuron's resting membrane potential is closest to the equilibrium potential for potassium because at rest the membrane is",
    opts=["impermeable to all ions","most permeable to potassium","most permeable to sodium","most permeable to calcium"],
    a=1, why="Resting permeability is dominated by potassium leak channels, so the membrane potential sits near, though not exactly at, the potassium equilibrium potential."),
  dict(q="Because action potentials are all-or-none, stimulus intensity is encoded by",
    opts=["action potential amplitude","action potential frequency and the number of active fibres","conduction velocity","resting potential magnitude"],
    a=1, why="Amplitude is fixed, so rate coding and population coding carry intensity information."),
  dict(q="Blocking voltage-gated sodium channels with a local anaesthetic prevents",
    opts=["the resting potential from forming","depolarisation from reaching and propagating past threshold","potassium leak","vesicle fusion only"],
    a=1, why="Without sodium influx the regenerative upstroke cannot occur, so signals fail to propagate even though the resting potential persists."),
  dict(q="Myelination increases conduction velocity because it",
    opts=["increases membrane capacitance","restricts current entry to nodes, allowing saltatory conduction","increases axon diameter tenfold","adds more sodium channels along the entire axon"],
    a=1, why="Insulation reduces capacitance and current leak between nodes, so depolarisation jumps node to node."),
  dict(q="A sound increases from 40 dB to 70 dB. The intensity has increased by a factor of",
    opts=["1.75","30","1000","300"],
    a=2, why="Each 10 dB is a tenfold intensity change, so 30 dB is 10 cubed, a factor of 1000."),
  dict(q="A corrective lens of -2.5 dioptres has a focal length of",
    opts=["-0.4 m, diverging","-2.5 m, diverging","0.4 m, converging","2.5 m, converging"],
    a=0, why="Focal length is the reciprocal of power: 1 divided by -2.5 gives -0.4 m, and a negative power indicates a diverging lens used for myopia."),
  dict(q="Space adaptation syndrome in the first days of flight is best explained by",
    opts=["reduced oxygen partial pressure","conflict between vestibular otolith signals and visual and proprioceptive input","direct radiation damage to the inner ear","elevated cabin carbon dioxide alone"],
    a=1, why="Otoliths no longer signal a gravitational vertical, producing sensory conflict until the central nervous system reweights its inputs."),
  dict(q="The basilar membrane encodes frequency because",
    opts=["hair cells fire at the frequency of the sound at all locations","its stiffness and width vary along its length, so different regions resonate at different frequencies","the ossicles filter frequencies mechanically","the auditory nerve performs a Fourier transform"],
    a=1, why="A mechanical gradient produces a tonotopic map, with high frequencies peaking near the stiff base and low frequencies near the apex."),
  dict(q="A student measures reaction time and finds a 30 ms increase after sleep restriction. The stage most likely responsible is",
    opts=["receptor transduction","central integration and decision","axonal conduction velocity","muscle contraction speed"],
    a=1, why="Peripheral transduction and conduction are relatively fixed; sleep loss primarily degrades central processing and attention."),
  dict(q="Chronically elevated cortisol during a long mission would be expected to",
    opts=["improve immune surveillance and bone deposition","suppress immune function and contribute to bone loss","have no measurable systemic effect","increase melatonin secretion at night"],
    a=1, why="Sustained glucocorticoid exposure is catabolic and immunosuppressive, compounding the unloading-driven skeletal problem."),
 ],
 applied=[
  ("Biophysics Set B: from a provided dataset of 30 reaction times under two conditions, compute means and standard deviations, plot the distributions, and state which stage of the stimulus-response chain your design can and cannot isolate.",
   "The limitation statement is the graded element; most student designs cannot separate integration from motor execution."),
  ("Trace the neural pathway from a light stimulus to a hand withdrawal, naming each structure. Then predict two measurable changes in that pathway's output after six months in microgravity and state how you would test each.",
   "Vestibular reweighting and postural control changes are the well-documented ones; visual acuity changes have a separate ocular mechanism."),
 ],
)

CONTENT["ch09"] = dict(
 bridge=("Circulation and respiration are fluid physics with biological plumbing. Both are reconfigured within hours of "
         "reaching orbit, when hydrostatic pressure gradients disappear and fluid shifts headward."),
 sections=[
  ("The heart and circulatory pressures", [
    "The heart is two pumps in series: the right side drives the low-pressure pulmonary circuit, the left the high-pressure systemic circuit. Cardiac output equals heart rate times stroke volume, and stroke volume depends on preload, contractility, and afterload. The Frank-Starling relationship links greater filling to greater ejection.",
    "Pressure falls along the systemic circuit, with the steepest drop across arterioles, the main resistance vessels. Poiseuille's relationship shows resistance varies inversely with the fourth power of radius, so a 20 per cent narrowing roughly doubles resistance. Standing on Earth adds a hydrostatic column that raises pressure in the feet and lowers it at the head, a gradient that vanishes in free fall."],
   ["cardiac output","preload","peripheral resistance","hydrostatic gradient"]),
  ("Blood and immunity", [
    "Blood transports gases, nutrients, wastes, hormones, and heat. Haemoglobin's cooperative binding produces a sigmoid oxygen dissociation curve that unloads oxygen efficiently in active tissue, shifted rightward by acidity, carbon dioxide, and temperature.",
    "Immunity is layered: physical and chemical barriers, then innate cellular and inflammatory responses, then adaptive humoral and cell-mediated responses with memory. Spaceflight studies report altered immune cell distribution, reduced T-cell responsiveness, and reactivation of latent herpesviruses, an effect attributed to combined stress, altered sleep, and microgravity."],
   ["Bohr effect","oxygen saturation","innate immunity","latent reactivation"]),
  ("Ventilation and gas exchange", [
    "Breathing is pressure-driven: diaphragm contraction increases thoracic volume, lowering intrapulmonary pressure below atmospheric so air flows in. Compliance, airway resistance, and surfactant determine the work of breathing. Gas exchange follows partial-pressure gradients across the alveolar membrane, described by Fick's law: flux scales with area and gradient and inversely with thickness.",
    "The gas laws structure the whole system. Boyle's law explains ventilation, Dalton's law gives the partial pressures that drive diffusion, and Henry's law governs dissolution in plasma. These same laws determine decompression risk during extravehicular activity, where reducing suit pressure demands prebreathing oxygen to wash out dissolved nitrogen."],
   ["compliance","partial pressure","Fick's law","decompression sickness"]),
  ("Integration and the orbital case", [
    "Within hours of orbital insertion, roughly two litres of fluid shift headward. Central volume receptors interpret this as overfilling, so diuresis reduces plasma volume, producing a smaller circulating volume and, on return to gravity, orthostatic intolerance. Cardiac mass declines modestly with reduced loading.",
    "Ocular changes grouped under spaceflight-associated neuro-ocular syndrome, including optic disc oedema and hyperopic shift, are linked to the same fluid redistribution and altered cerebrospinal fluid dynamics. Both cases show the general lesson: physiological set points are calibrated to a gravitational environment, and removing gravity is a systematic perturbation rather than a nuisance variable."],
   ["cephalad fluid shift","orthostatic intolerance","plasma volume","SANS"]),
 ],
 figure=dict(kind="flow", title="The oxygen cascade",
   caption="Oxygen moves down a partial-pressure gradient at every step. A fault anywhere in the chain presents as tissue hypoxia, so diagnosis means locating which gradient failed.",
   items=["Atmospheric O2","Alveolar gas","Pulmonary capillary","Arterial blood","Tissue capillary","Mitochondrion"]),
 practice=[
  dict(q="An arteriole constricts to 80 per cent of its original radius. Resistance changes by a factor of approximately",
    opts=["1.25","2.44","0.41","4.0"],
    a=1, why="Resistance varies as the inverse fourth power of radius: 0.8 to the fourth is 0.41, and its reciprocal is about 2.44, so resistance roughly doubles and a half."),
  dict(q="Cardiac output equals",
    opts=["heart rate divided by stroke volume","heart rate multiplied by stroke volume","stroke volume divided by preload","mean arterial pressure multiplied by resistance"],
    a=1, why="Output is volume per beat times beats per minute; at 70 beats and 70 millilitres this gives about 4.9 litres per minute."),
  dict(q="A rightward shift of the oxygen dissociation curve means haemoglobin",
    opts=["binds oxygen more tightly at every partial pressure","releases oxygen more readily to tissues","carries more carbon dioxide only","cannot bind oxygen in the lungs"],
    a=1, why="Acidity, carbon dioxide, temperature, and 2,3-BPG lower affinity, favouring unloading precisely where metabolism is high."),
  dict(q="Headward fluid shift in orbit leads to reduced plasma volume because central receptors interpret the shift as",
    opts=["dehydration, triggering fluid retention","volume overload, triggering diuresis","haemorrhage, triggering vasoconstriction","hypoxia, triggering hyperventilation"],
    a=1, why="Stretch receptors in the atria and great vessels signal apparent overfilling, so the kidneys excrete fluid and total plasma volume falls."),
  dict(q="Post-flight orthostatic intolerance is best explained by the combination of",
    opts=["increased plasma volume and increased baroreflex gain","reduced plasma volume and blunted baroreflex response on re-exposure to gravity","excess red cell mass","increased cardiac contractility"],
    a=1, why="A smaller circulating volume plus a deconditioned reflex response leaves blood pressure unsupported on standing."),
  dict(q="Prebreathing pure oxygen before extravehicular activity is required to",
    opts=["increase lung compliance","wash out dissolved nitrogen and reduce decompression sickness risk","raise body temperature","reduce carbon dioxide retention"],
    a=1, why="Lowering suit pressure allows dissolved nitrogen to form bubbles, per Henry's law; denitrogenation removes the dissolved gas first."),
  dict(q="Fick's law predicts that gas exchange decreases when",
    opts=["alveolar surface area is reduced or the membrane thickens","the partial pressure gradient increases","cardiac output rises","haemoglobin concentration rises"],
    a=0, why="Flux scales with area and gradient and inversely with distance, so emphysema (area loss) and fibrosis or oedema (thickening) both impair exchange."),
  dict(q="Surfactant reduces the work of breathing by",
    opts=["increasing alveolar surface tension","reducing surface tension and preventing small alveoli from collapsing","thickening the alveolar wall","increasing airway resistance"],
    a=1, why="Lower surface tension reduces the pressure needed to inflate alveoli and stabilises alveoli of different sizes, per the Laplace relationship."),
  dict(q="Reactivation of latent viruses during long missions is generally attributed to",
    opts=["direct radiation activation of viral genomes only","stress-related immune modulation combined with altered sleep and microgravity effects","cabin oxygen concentration","reduced dietary protein alone"],
    a=1, why="The evidence points to multifactorial immune modulation, with elevated stress hormones and disturbed circadian patterns as major contributors."),
  dict(q="The most defensible statement about SANS is that it is",
    opts=["fully explained and reversible in all cases","associated with cephalad fluid shift and altered cerebrospinal fluid dynamics, with mechanisms still under investigation","caused solely by radiation exposure","identical to terrestrial glaucoma"],
    a=1, why="Association is established; causation is not fully resolved, and residual structural changes have been reported in some crew members."),
 ],
 applied=[
  ("From a provided dataset of blood pressure, heart rate, and stroke volume before, during, and after simulated microgravity (head-down bed rest), compute cardiac output and total peripheral resistance at each stage and interpret the trajectory.",
   "Look for recognition that resistance changes may compensate for volume loss, masking it in mean pressure."),
  ("A crew member reports breathlessness during an extravehicular activity. Working from the oxygen cascade, list four possible failure points, the measurement that would distinguish each, and the order in which you would check them.",
   "Ordering by consequence and by speed of measurement is the graded reasoning."),
 ],
)

CONTENT["ch10"] = dict(
 bridge=("Closing Term 2 means treating the body as one integrated system, which is exactly the framing needed in Week 14 "
         "when the system in question is a sealed habitat and the loops to be closed are water, oxygen, carbon, and waste."),
 sections=[
  ("Digestion, absorption, and metabolic fuel", [
    "The alimentary canal mechanically and chemically breaks food into absorbable units: carbohydrates to monosaccharides, proteins to amino acids, lipids to fatty acids and monoglycerides. Absorption occurs mostly in the small intestine, whose villi and microvilli amplify surface area enormously. Accessory organs supply enzymes and bile.",
    "Metabolically, the body alternates between absorptive and postabsorptive states under insulin and glucagon control, with glycogen as the short-term store and adipose tissue as the dense long-term store. Basal metabolic rate accounts for most daily expenditure, and it sets the food, oxygen, and heat-rejection budget of any closed habitat."],
   ["villus","enzymatic hydrolysis","glycogen","basal metabolic rate"]),
  ("Renal function and fluid balance", [
    "The nephron filters, reabsorbs, secretes, and excretes. Glomerular filtration is pressure-driven and largely non-selective by size; selectivity comes from tubular reabsorption, which recovers water, glucose, amino acids, and ions. The countercurrent multiplier in the loop of Henle establishes a medullary osmotic gradient that permits concentrated urine.",
    "Antidiuretic hormone regulates water permeability of the collecting duct, and aldosterone regulates sodium reabsorption and thus volume. Osmosis and osmolarity are the physical core: cells shrink in hypertonic and swell in hypotonic surroundings, so plasma osmolarity is defended within a narrow band."],
   ["glomerular filtration","countercurrent multiplier","osmolarity","aldosterone"]),
  ("Reproduction and development", [
    "Gametogenesis, fertilisation, cleavage, implantation, and organogenesis proceed under hormonal control from the hypothalamic-pituitary-gonadal axis. Development is highly sensitive to environmental perturbation during specific critical windows.",
    "For space life science this raises questions that remain largely unanswered: mammalian reproduction and development in altered gravity and elevated radiation have been studied only in limited animal models, and no human data exist. Honest treatment of this gap, rather than confident extrapolation, is part of the scientific standard the course expects."],
   ["gametogenesis","organogenesis","critical window","teratogen"]),
  ("Integrating the systems", [
    "Homeostatic variables are defended by multiple systems acting together. Blood pressure control involves heart, vessels, kidneys, and endocrine signals; acid-base balance involves buffers, ventilation, and renal excretion on three different timescales, from seconds to days.",
    "Multi-system integration is also how failure propagates. Dehydration reduces plasma volume, which reduces stroke volume, which raises heart rate and lowers renal perfusion, which further concentrates plasma. Recognising these cascades is the analytical skill Term 2 is meant to leave behind, and it transfers directly to habitat systems, where a single failed loop propagates in the same way."],
   ["acid-base balance","buffer system","cascade failure","redundancy"]),
 ],
 figure=dict(kind="flow", title="Water through the body",
   caption="Every arrow is a rate that a closed habitat must also account for. Human water turnover is the largest single consumable in mission planning.",
   items=["Intake (drink, food, metabolic)","Absorption (small intestine)","Plasma and interstitial pools","Renal filtration and reabsorption","Loss (urine, sweat, respiration, faeces)"]),
 practice=[
  dict(q="Glomerular filtration is best described as",
    opts=["selective transport of solutes by carrier proteins","pressure-driven, largely size-selective filtration of plasma","active secretion of wastes only","reabsorption of water from the collecting duct"],
    a=1, why="Filtration is bulk and non-specific by size and charge; specificity arises downstream in tubular reabsorption and secretion."),
  dict(q="Antidiuretic hormone increases water reabsorption by",
    opts=["increasing glomerular filtration rate","inserting water channels into collecting duct membranes","increasing sodium excretion","reducing medullary osmolarity"],
    a=1, why="ADH promotes aquaporin insertion, so water follows the medullary osmotic gradient out of the duct."),
  dict(q="A crew member's plasma osmolarity rises. The expected homeostatic response is",
    opts=["increased ADH secretion and thirst","decreased ADH and increased urine volume","increased aldosterone only, with no thirst response","reduced sodium reabsorption"],
    a=0, why="Osmoreceptors drive both ADH release and thirst, conserving water and prompting intake."),
  dict(q="The countercurrent multiplier is essential because it",
    opts=["filters plasma at the glomerulus","creates the medullary osmotic gradient that makes concentrated urine possible","secretes potassium into the tubule","produces bile for lipid absorption"],
    a=1, why="Without the gradient, water could not be reabsorbed from the collecting duct and urine could not be concentrated above plasma osmolarity."),
  dict(q="During a marathon in the heat, the dominant route of water loss is",
    opts=["urine","evaporative loss through sweat and respiration","faecal water","metabolic water production"],
    a=1, why="Sweating can exceed a litre per hour, dwarfing renal output, which is simultaneously reduced by ADH and reduced renal perfusion."),
  dict(q="Acid-base balance is defended on three timescales. The fastest is",
    opts=["renal bicarbonate handling","chemical buffering in blood and cells","respiratory adjustment of carbon dioxide","hepatic ammonia processing"],
    a=1, why="Buffers act in seconds, ventilation in minutes, and renal compensation over hours to days."),
  dict(q="Which statement about human reproduction in spaceflight is scientifically accurate as of the current evidence base?",
    opts=["Human conception and gestation in space have been studied in several crewed missions","No human data exist; conclusions rest on limited animal models","Animal studies show no effects of altered gravity on development","Radiation has been shown to have no developmental effect"],
    a=1, why="The gap is real and must be stated as a gap. Rodent and invertebrate studies show effects but do not license confident human extrapolation."),
  dict(q="Basal metabolic rate matters to habitat design primarily because it sets",
    opts=["the crew's exercise schedule","the oxygen, food, water, and heat-rejection budget","the radiation shielding thickness","the cabin pressure"],
    a=1, why="BMR drives consumables and thermal load, which are the mass and power drivers in life-support sizing."),
  dict(q="A cascade in which dehydration lowers stroke volume, raising heart rate and lowering renal perfusion, illustrates",
    opts=["independent regulation of each system","coupled multi-system failure propagation","positive feedback that is beneficial","a purely renal disorder"],
    a=1, why="The coupling is the point: interventions must target the driving variable, plasma volume, not the downstream signs."),
  dict(q="Insulin's principal metabolic effect after a meal is to",
    opts=["promote glucose uptake and storage as glycogen and fat","stimulate glycogen breakdown","increase gluconeogenesis","raise blood glucose"],
    a=0, why="Insulin is the absorptive-state hormone; glucagon drives the opposing postabsorptive mobilisation."),
 ],
 applied=[
  ("Build an integrated organ-system map for a single perturbation, such as 24 hours without water or a 10 per cent blood loss. Show every system that responds, the direction of each response, and the timescale.",
   "Timescales separate a good map from a list; expect seconds to days to be represented."),
  ("Term 2 synthesis: write the human physiology section of a mission risk register. List five physiological risks of a 12-month mission, the mechanism of each, the countermeasure, and the residual uncertainty.",
   "Residual uncertainty is the column that connects this task to Weeks 14 and 15."),
 ],
)
